#!/sbin/runscript
# $Header: /var/cvsroot/gentoo-x86/dev-db/redis/files/redis.initd,v 1.4 2012/02/04 21:17:55 swegener Exp $

REDIS_EXEC=/usr/sbin/redis-server
REDIS_PID=${REDIS_PID:-/var/run/redis/redis.pid}
REDIS_DIR=${REDIS_DIR:-/var/lib/redis}
REDIS_CONF=${REDIS_CONF:-/etc/redis.conf}
REDIS_OPTS=${REDIS_OPTS:-"${REDIS_CONF}"}
REDIS_USER=${REDIS_USER:-redis}
REDIS_GROUP=${REDIS_GROUP:-redis}

depend() {
	use net localmount logger
	after keepalived
}

start() {

	local PID_DIR=$(dirname ${REDIS_PID})
	mkdir -p ${PID_DIR}
	chown ${REDIS_USER}:${REDIS_GROUP} ${PID_DIR}

	ebegin "Starting Redis server"
	start-stop-daemon --start \
		--chdir "${REDIS_DIR}" \
		--user ${REDIS_USER}:${REDIS_GROUP} \
		--pidfile "${REDIS_PID}" \
		--exec "${REDIS_EXEC}" \
		-- ${REDIS_OPTS}
	ret=$?
	eend ${ret}

}

stop() {
	ebegin "Stopping Redis server"
	start-stop-daemon --stop --quiet --pidfile "${REDIS_PID}"
	ret=$?
	rm -f "${REDIS_PID}"
	eend ${ret}
}
