#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

PIDFILE="/var/run/tntnet.pid"

depend() {
	use net
}

start() {
	ebegin "Starting tntnet"
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec /usr/bin/tntnet
	eend $?
}

stop() {
	ebegin "Stopping tntnet"
	start-stop-daemon --stop --pidfile $PIDFILE --exec /usr/bin/tntnet
	eend $?
}

reload() {
	ebegin "Reloading tntnet configuration"
	start-stop-daemon --pidfile $PIDFILE --signal HUP --exec /usr/bin/tntnet
	eend $?
}
