# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Sized functors, for size-based enumerations"
HOMEPAGE="https://hackage.haskell.org/package/size-based"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"

RDEPEND=">=dev-haskell/dictionary-sharing-0.1:=[profile?] <dev-haskell/dictionary-sharing-1.0:=[profile?]
	>=dev-haskell/testing-type-modifiers-0.1:=[profile?] <dev-haskell/testing-type-modifiers-1.0:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
