#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

PIDDIR="/run/${SVCNAME}"

description="Sigh is a milter that signs emails with S/MIME"
name="S/MIME signing milter"
pidfile="${PIDDIR}/${SVCNAME}.pid"
command="/usr/sbin/sigh"
command_args="-p ${pidfile} ${OPTIONS}"
retry="30"

depend() {
	need localmount net
	use mta logger
}

start_pre() {
	checkpath -q -d -o sigh:sigh -m 0755 "${PIDDIR}" || return 1
}

