#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

command="/usr/bin/irkerd"
command_args="${IRKERD_OPTS}"
pidfile="/var/run/${SVCNAME}.pid"

depend() {
	use net
}

start () {
	ebegin "Starting irkerd"
	start-stop-daemon --start --quiet --exec $command
	eend $?
}

stop() {
        ebegin "Stopping irkerd"
        start-stop-daemon --stop --quiet --exec $command
        eend $?
}

