# Copyright 2022-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.10

EAPI=8

CRATES="
	anstream@0.6.15
	anstyle-parse@0.2.5
	anstyle-query@1.1.1
	anstyle-wincon@3.0.4
	anstyle@1.0.8
	autocfg@1.3.0
	bitflags@2.6.0
	cfg-if@1.0.0
	clap@4.5.15
	clap_builder@4.5.15
	clap_lex@0.7.2
	colorchoice@1.0.2
	dashmap@5.5.3
	diff@0.1.13
	equivalent@1.0.1
	errno@0.3.9
	fastrand@2.1.0
	hashbrown@0.14.5
	heck@0.4.1
	indexmap@2.3.0
	is_terminal_polyfill@1.70.1
	itoa@1.0.11
	lazy_static@1.5.0
	libc@0.2.155
	linux-raw-sys@0.4.14
	lock_api@0.4.12
	log@0.4.22
	memchr@2.7.4
	once_cell@1.19.0
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	pretty_assertions@1.4.0
	proc-macro2@1.0.86
	quote@1.0.36
	redox_syscall@0.5.3
	rustix@0.38.34
	ryu@1.0.18
	scopeguard@1.2.0
	serde@1.0.205
	serde_derive@1.0.205
	serde_json@1.0.122
	serde_spanned@0.6.7
	serial_test@2.0.0
	serial_test_derive@2.0.0
	smallvec@1.13.2
	strsim@0.11.1
	syn@2.0.72
	tempfile@3.12.0
	toml@0.8.19
	toml_datetime@0.6.8
	toml_edit@0.22.20
	unicode-ident@1.0.12
	utf8parse@0.2.2
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	winnow@0.6.18
	yansi@0.5.1
"

inherit cargo

DESCRIPTION="A tool for generating C bindings to Rust code"
HOMEPAGE="https://github.com/mozilla/cbindgen/"
SRC_URI="${CARGO_CRATE_URIS}
	https://github.com/mozilla/cbindgen/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="MPL-2.0"
# Dependent crate licenses
LICENSE+="
	MIT Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64 ~arm ~arm64 ~loong ~ppc64 ~riscv ~x86"
IUSE="test"

# Needs debugging enabled and lots of other problems.
# https://github.com/mozilla/cbindgen/issues?q=is%3Aissue+is%3Aopen+test
RESTRICT="test"

BDEPEND="test? ( dev-build/cmake )"

QA_FLAGS_IGNORED="usr/bin/cbindgen"
