# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/system-fileio/system-fileio-0.3.11.ebuild,v 1.1 2013/08/26 11:00:45 qnikst Exp $

EAPI=5

# ebuild generated by hackport 0.3.1

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Consistent filesystem interaction across GHC versions"
HOMEPAGE="https://john-millikin.com/software/haskell-filesystem/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/system-filepath-0.3.1:=[profile?]
		<dev-haskell/system-filepath-0.5:=[profile?]
		>=dev-haskell/text-0.7.1:=[profile?]
		<dev-haskell/text-0.12:=[profile?]
		>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
