#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the Erlang Public License 1.1
# $Header: /var/cvsroot/gentoo-x86/dev-lang/erlang/files/epmd.init,v 1.2 2012/12/31 09:24:49 djc Exp $

depend() {
	need net
}

start() {
	ebegin "Starting Erlang Port Mapper Daemon"
	start-stop-daemon --start --quiet --user nobody --group nobody --exec /usr/bin/epmd -- -daemon
	eend $?
}

stop() {
	ebegin "Stopping Erlang Port Mapper Daemon"
	/usr/bin/epmd -kill >/dev/null
	eend $?
}
