#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
        need localmount
}

start() {
        ebegin "Starting sendpage"
        start-stop-daemon --start --exec /usr/bin/sendpage -- -bd
        eend ${?}
}

stop() {
        ebegin "Stopping sendpage"
        start-stop-daemon --stop -n sendpage
        eend ${?}
}

