# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/vector-th-unbox/vector-th-unbox-0.2.1.0.ebuild,v 1.1 2014/07/02 14:19:30 gienah Exp $

EAPI=5

# ebuild generated by hackport 0.4.9999

CABAL_FEATURES="lib profile test-suite" # haddock hoogle hscolour, UTF-8
inherit haskell-cabal

DESCRIPTION="Deriver for Data.Vector.Unboxed using Template Haskell"
HOMEPAGE="http://hackage.haskell.org/package/vector-th-unbox"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/vector-0.7:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	test? ( dev-haskell/data-default
		dev-haskell/vector )
"
