#!/sbin/openrc-run
# Copyright 2016-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Prometheus memcached exporter"
pidfile="/var/run/${RC_SVCNAME}.pid"
command="/usr/bin/memcached_exporter"
command_user=${user:-${RC_SVCNAME}}
group=${group:-${RC_SVCNAME}}
command_background="true"
errror_log="/var/log/${RC_SVCNAME}/${RC_SVCNAME}.log"
output_log="/var/log/${RC_SVCNAME}/${RC_SVCNAME}.log"
start_stop_daemon_args="--group ${group}"
