#!/sbin/openrc-run
# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Maintain persistent software state in the NVIDIA driver"
command="nvidia-persistenced"
command_args="${NVPD_USER:+--user ${NVPD_USER}} ${ARGS}"
pidfile="/var/run/nvidia-persistenced/nvidia-persistenced.pid"

stop_post() {
	rmdir "${pidfile%/*}" 2>/dev/null || true
}
