#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start() {
	ebegin "Starting atokx2"
	start-stop-daemon -b --start --quiet --exec /opt/atokx2/sbin/atokx2mngdaemon
	eend $?
}

stop() {
	ebegin "Stopping atokx2"
	start-stop-daemon --stop --quiet --exec /opt/atokx2/sbin/atokx2mngdaemon
	eend $?
}
