# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI="5"

TEXLIVE_MODULE_CONTENTS="IEEEconf IEEEtran aastex abntex2 acmart acmconf active-conf adfathesis afparticle afthesis aguplus aiaa ametsoc anufinalexam aomart apa apa6 apa6e arsclassica articleingud asaetr ascelike aucklandthesis bangorcsthesis bangorexam beamer-FUBerlin beamer-verona bgteubner br-lex brandeis-dissertation cascadilla chem-journal classicthesis cleanthesis cmpj confproc cquthesis dccpaper dithesis ebook ebsthesis ejpecp ekaia elbioimp elsarticle elteikthesis emisa erdc estcpmm fbithesis fcavtex fcltxdoc fei gaceta gatech-thesis gradstudentresume grant gsemthesis gzt h2020proposal har2nat hobete hustthesis icsv ieeepes ijmart ijsra imac imtekda iscram jacow jmlr jpsj kdgdocs kluwer ksp-thesis langsci lion-msc lni lps matc3 matc3mem mcmthesis mentis mnras msu-thesis mucproc mugsthesis musuos muthesis mynsfc nature navydocs nddiss ndsu-thesis novel nwejm nih nihbiosketch nostarch nrc onrannual opteng philosophersimprint pittetd pkuthss powerdot-FUBerlin pracjourn procIAGssymp proposal ptptex psu-thesis resphilosophica resumecls revtex revtex4 ryethesis sageep sapthesis scrjrnl schule sduthesis seuthesis seuthesix soton sphdthesis spie sr-vorl stellenbosch suftesi sugconf tabriz-thesis texilikechaps texilikecover thesis-ekf thesis-titlepage-fhac thuthesis toptesi tudscr tugboat tugboat-plain turabian tui uaclasses uafthesis uantwerpendocs ucbthesis ucdavisthesis ucthesis uestcthesis uhhassignment uiucredborder uiucthesis ulthese umbclegislation umthesis umich-thesis unamth-template unamthesis unswcover uothesis urcls uowthesis uowthesistitlepage uspatent ut-thesis uwthesis vancouver xduthesis wsemclassic xcookybooky yathesis york-thesis collection-publishers
"
TEXLIVE_MODULE_DOC_CONTENTS="IEEEconf.doc IEEEtran.doc aastex.doc abntex2.doc acmart.doc acmconf.doc active-conf.doc adfathesis.doc afparticle.doc afthesis.doc aguplus.doc aiaa.doc ametsoc.doc anufinalexam.doc aomart.doc apa.doc apa6.doc apa6e.doc arsclassica.doc articleingud.doc asaetr.doc ascelike.doc aucklandthesis.doc bangorcsthesis.doc bangorexam.doc beamer-FUBerlin.doc beamer-verona.doc bgteubner.doc br-lex.doc brandeis-dissertation.doc cascadilla.doc classicthesis.doc cleanthesis.doc cmpj.doc confproc.doc cquthesis.doc dccpaper.doc dithesis.doc ebook.doc ebsthesis.doc ejpecp.doc ekaia.doc elbioimp.doc elsarticle.doc elteikthesis.doc emisa.doc erdc.doc estcpmm.doc fbithesis.doc fcavtex.doc fcltxdoc.doc fei.doc gaceta.doc gatech-thesis.doc gradstudentresume.doc grant.doc gsemthesis.doc gzt.doc h2020proposal.doc har2nat.doc hobete.doc hustthesis.doc icsv.doc ieeepes.doc ijmart.doc ijsra.doc imac.doc imtekda.doc iscram.doc jacow.doc jmlr.doc jpsj.doc kdgdocs.doc kluwer.doc ksp-thesis.doc langsci.doc lion-msc.doc lni.doc lps.doc matc3.doc matc3mem.doc mcmthesis.doc mentis.doc mnras.doc msu-thesis.doc mucproc.doc mugsthesis.doc musuos.doc muthesis.doc mynsfc.doc nature.doc navydocs.doc nddiss.doc ndsu-thesis.doc novel.doc nwejm.doc nih.doc nihbiosketch.doc nostarch.doc nrc.doc onrannual.doc opteng.doc philosophersimprint.doc pittetd.doc pkuthss.doc powerdot-FUBerlin.doc pracjourn.doc procIAGssymp.doc proposal.doc ptptex.doc psu-thesis.doc resphilosophica.doc resumecls.doc revtex.doc revtex4.doc ryethesis.doc sageep.doc sapthesis.doc scrjrnl.doc schule.doc sduthesis.doc seuthesis.doc seuthesix.doc soton.doc sphdthesis.doc spie.doc sr-vorl.doc stellenbosch.doc suftesi.doc sugconf.doc tabriz-thesis.doc thesis-ekf.doc thesis-titlepage-fhac.doc thuthesis.doc toptesi.doc tudscr.doc tugboat.doc tugboat-plain.doc turabian.doc tui.doc uaclasses.doc uafthesis.doc uantwerpendocs.doc ucbthesis.doc ucdavisthesis.doc ucthesis.doc uestcthesis.doc uhhassignment.doc uiucredborder.doc uiucthesis.doc ulthese.doc umbclegislation.doc umthesis.doc umich-thesis.doc unamth-template.doc unamthesis.doc unswcover.doc uothesis.doc urcls.doc uowthesis.doc uowthesistitlepage.doc uspatent.doc ut-thesis.doc uwthesis.doc vancouver.doc xduthesis.doc wsemclassic.doc xcookybooky.doc yathesis.doc york-thesis.doc "
TEXLIVE_MODULE_SRC_CONTENTS="IEEEconf.source acmart.source acmconf.source active-conf.source adfathesis.source afparticle.source aiaa.source aomart.source apa6.source apa6e.source articleingud.source bangorcsthesis.source bangorexam.source bgteubner.source brandeis-dissertation.source confproc.source cquthesis.source dccpaper.source ebsthesis.source ejpecp.source ekaia.source elbioimp.source elsarticle.source elteikthesis.source emisa.source erdc.source estcpmm.source fbithesis.source fcltxdoc.source fei.source grant.source gsemthesis.source gzt.source hustthesis.source icsv.source ijmart.source imtekda.source jmlr.source kdgdocs.source kluwer.source lni.source lps.source matc3.source matc3mem.source mcmthesis.source mentis.source mucproc.source mugsthesis.source musuos.source mynsfc.source navydocs.source nddiss.source nwejm.source nostarch.source nrc.source philosophersimprint.source pittetd.source pracjourn.source proposal.source resphilosophica.source resumecls.source revtex.source revtex4.source ryethesis.source sageep.source scrjrnl.source schule.source sduthesis.source seuthesis.source seuthesix.source sr-vorl.source stellenbosch.source suftesi.source thesis-ekf.source thesis-titlepage-fhac.source thuthesis.source toptesi.source tudscr.source tugboat.source uaclasses.source uantwerpendocs.source ucdavisthesis.source uhhassignment.source uiucredborder.source uiucthesis.source ulthese.source uothesis.source xduthesis.source wsemclassic.source xcookybooky.source yathesis.source york-thesis.source "
inherit  texlive-module
DESCRIPTION="TeXLive Publisher styles, theses, etc."

LICENSE=" Apache-2.0 BSD GPL-1 GPL-2 GPL-3 LPPL-1.2 LPPL-1.3 LPPL-1.3c OFL public-domain TeX-other-free "
SLOT="0"
KEYWORDS="~alpha amd64 ~arm ~arm64 ~hppa ia64 ~mips ~ppc ~ppc64 ~s390 ~sh ~sparc x86 ~amd64-fbsd ~x86-fbsd ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~x64-solaris ~x86-solaris"
IUSE=""
DEPEND=">=dev-texlive/texlive-latex-2017
!<dev-texlive/texlive-latexextra-2014
"
RDEPEND="${DEPEND} "
