# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="JMCNAMARA"
DIST_VERSION="1.09"

inherit perl-module

DESCRIPTION="Create a new file in the Excel 2007+ XLSX format."

LICENSE="Artistic"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND=">=dev-perl/Archive-Zip-1.680.0"

BDEPEND="${RDEPEND}"
