#!/sbin/openrc-run
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	use clock logger
	need localmount
}

start() {
	ebegin "Starting incrond"
	start-stop-daemon --start --pidfile /var/run/incrond.pid --exec /usr/sbin/incrond -- -f /etc/incron.conf
	eend $?
}

stop() {
	ebegin "Stopping incrond"
	start-stop-daemon --stop --pidfile /var/run/incrond.pid
	eend $?
}
