#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command=/usr/bin/fluentd
logfile=/var/log/fluentd/fluent.log
pidfile=/var/run/fluentd.pid
command_args="--daemon ${pidfile} --no-supervisor -o ${logfile} ${fluentd_opts}"
command_background=yes
command_user=fluentd:fluentd
retry="${retry:-TERM/10/KILL/30}"

start_pre() {
	fluentd -q --dry-run
}
