#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

config="/etc/${RC_SVCNAME}.conf"
name="IGMPproxy"
pidfile="/run/${RC_SVCNAME}.pid"

command="igmpproxy"
command_args="${IGMPPROXY_OPTS} ${config}"
procname="${RC_SVCNAME}"

start_pre() {
	if [ ! -f "${config}" ]; then
		eerror "Please create ${config} before starting ${name}!"
		return 1
	else
		return 0
	fi
}
