# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI="5"

TEXLIVE_MODULE_CONTENTS="Asana-Math accanthis adforn adfsymbols aecc alegreya allrunes almfixed anonymouspro antiqua antt archaic arev ascii-font aspectratio astro augie auncial-new aurical b1encoding barcodes baskervald baskervaldx bbding bbm bbm-macros bbold bbold-type1 belleek bera berenisadf bguq blacklettert1 boisik bookhands boondox braille brushscr cabin caladea calligra calligra-type1 cantarell carlito carolmin-ps ccicons cfr-lm cherokee cinzel clearsans cm-lgc cm-unicode cmbright cmll cmpica cmtiup comfortaa concmath-fonts cookingsymbols countriesofeurope courier-scaled cryst cyklop dancers dantelogo dejavu dice dictsym dingbat doublestroke dozenal drm droid duerer duerer-latex dutchcal ean ebgaramond ebgaramond-maths ecc eco eiad eiad-ltx electrum elvish epigrafica epsdice erewhon esstix esvect eulervm euxm fbb fdsymbol fetamont feyn fge fira foekfont fonetika fontawesome fourier fouriernc frcursive genealogy gentium-tug gfsartemisia gfsbodoni gfscomplutum gfsdidot gfsneohellenic gfssolomos gillcm gillius gnu-freefont gothic greenpoint grotesq hacm hands heuristica hfbright hfoldsty ifsym inconsolata initials ipaex-type1 iwona jablantile jamtimes junicode kixfont knuthotherfonts kpfonts kurier lato lfb libertine librebaskerville librecaslon libris linearA lobster2 lxfonts ly1 mathabx mathabx-type1 mathdesign mdputu mdsymbol merriweather mintspirit mnsymbol newpx newtx newtxtt nkarta obnov ocherokee ocr-b ocr-b-outline ogham oinuit oldlatin oldstandard opensans orkhun overlock pacioli paratype phaistos phonetic pigpen playfair poltawski prodint punk punk-latex punknova pxtxalfa quattrocento raleway recycle roboto romande rsfso sansmathaccent sansmathfonts sauter sauterfonts schulschriften semaphor skull sourcecodepro sourcesanspro starfont staves stix superiors tapir tengwarscript tfrupee tpslifonts trajan txfontsb umtypewriter universa universalis urwchancal venturisadf wsuipa xcharter xits yfonts zlmtt collection-fontsextra
"
TEXLIVE_MODULE_DOC_CONTENTS="Asana-Math.doc accanthis.doc adforn.doc adfsymbols.doc aecc.doc alegreya.doc allrunes.doc almfixed.doc anonymouspro.doc antiqua.doc antt.doc archaic.doc arev.doc ascii-font.doc aspectratio.doc astro.doc augie.doc auncial-new.doc aurical.doc b1encoding.doc barcodes.doc baskervald.doc baskervaldx.doc bbding.doc bbm.doc bbm-macros.doc bbold.doc bbold-type1.doc belleek.doc bera.doc berenisadf.doc bguq.doc blacklettert1.doc boisik.doc bookhands.doc boondox.doc braille.doc brushscr.doc cabin.doc caladea.doc calligra.doc calligra-type1.doc cantarell.doc carlito.doc carolmin-ps.doc ccicons.doc cfr-lm.doc cherokee.doc cinzel.doc clearsans.doc cm-lgc.doc cm-unicode.doc cmbright.doc cmll.doc cmpica.doc cmtiup.doc comfortaa.doc concmath-fonts.doc cookingsymbols.doc countriesofeurope.doc courier-scaled.doc cryst.doc cyklop.doc dantelogo.doc dejavu.doc dice.doc dictsym.doc dingbat.doc doublestroke.doc dozenal.doc drm.doc droid.doc duerer.doc duerer-latex.doc dutchcal.doc ean.doc ebgaramond.doc ebgaramond-maths.doc ecc.doc eco.doc eiad.doc eiad-ltx.doc electrum.doc elvish.doc epigrafica.doc epsdice.doc erewhon.doc esstix.doc esvect.doc eulervm.doc fbb.doc fdsymbol.doc fetamont.doc feyn.doc fge.doc fira.doc foekfont.doc fonetika.doc fontawesome.doc fourier.doc fouriernc.doc frcursive.doc genealogy.doc gentium-tug.doc gfsartemisia.doc gfsbodoni.doc gfscomplutum.doc gfsdidot.doc gfsneohellenic.doc gfssolomos.doc gillcm.doc gillius.doc gnu-freefont.doc gothic.doc greenpoint.doc grotesq.doc hacm.doc heuristica.doc hfbright.doc hfoldsty.doc ifsym.doc inconsolata.doc initials.doc ipaex-type1.doc iwona.doc jablantile.doc jamtimes.doc junicode.doc kixfont.doc kpfonts.doc kurier.doc lato.doc lfb.doc libertine.doc librebaskerville.doc librecaslon.doc libris.doc linearA.doc lobster2.doc lxfonts.doc ly1.doc mathabx.doc mathabx-type1.doc mathdesign.doc mdputu.doc mdsymbol.doc merriweather.doc mintspirit.doc mnsymbol.doc newpx.doc newtx.doc newtxtt.doc nkarta.doc obnov.doc ocherokee.doc ocr-b.doc ocr-b-outline.doc ogham.doc oinuit.doc oldlatin.doc oldstandard.doc opensans.doc orkhun.doc overlock.doc pacioli.doc paratype.doc phaistos.doc phonetic.doc pigpen.doc playfair.doc poltawski.doc prodint.doc punk.doc punk-latex.doc punknova.doc pxtxalfa.doc quattrocento.doc raleway.doc recycle.doc roboto.doc romande.doc rsfso.doc sansmathaccent.doc sansmathfonts.doc sauterfonts.doc schulschriften.doc semaphor.doc sourcecodepro.doc sourcesanspro.doc starfont.doc staves.doc stix.doc superiors.doc tapir.doc tengwarscript.doc tfrupee.doc tpslifonts.doc trajan.doc txfontsb.doc universa.doc universalis.doc urwchancal.doc venturisadf.doc wsuipa.doc xcharter.doc xits.doc yfonts.doc zlmtt.doc "
TEXLIVE_MODULE_SRC_CONTENTS="allrunes.source anonymouspro.source archaic.source arev.source ascii-font.source auncial-new.source b1encoding.source barcodes.source baskervald.source bbding.source bbm-macros.source bbold.source belleek.source bguq.source blacklettert1.source bookhands.source cantarell.source ccicons.source cfr-lm.source cmbright.source cmll.source comfortaa.source cookingsymbols.source dingbat.source dozenal.source drm.source droid.source eco.source eiad-ltx.source electrum.source epsdice.source esvect.source eulervm.source fdsymbol.source fetamont.source feyn.source fge.source fourier.source gentium-tug.source gnu-freefont.source hfoldsty.source lato.source libris.source linearA.source lxfonts.source mdsymbol.source mnsymbol.source nkarta.source ocr-b-outline.source oinuit.source oldstandard.source opensans.source pacioli.source phaistos.source romande.source sauterfonts.source skull.source staves.source stix.source tengwarscript.source tfrupee.source tpslifonts.source trajan.source txfontsb.source universa.source venturisadf.source xits.source yfonts.source "
inherit  texlive-module
DESCRIPTION="TeXLive Additional fonts"

LICENSE=" Apache-2.0 BSD GPL-1 GPL-2 GPL-3 LPPL-1.2 LPPL-1.3 OFL public-domain TeX TeX-other-free "
SLOT="0"
KEYWORDS="~alpha amd64 arm ~hppa ~mips ppc ~ppc64 ~s390 ~sh x86 ~amd64-fbsd ~x86-fbsd ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~x64-solaris ~x86-solaris"
IUSE=""
DEPEND=">=dev-texlive/texlive-basic-2014
!=dev-texlive/texlive-langpolish-2007*
"
RDEPEND="${DEPEND} "
