#!/sbin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id: mod-mono-server-r1.initd,v 1.1 2012/01/22 12:54:29 pacho Exp $

depend() {
	use net
	after dotnet
}

start() {
	[ -z "$MonoServerRootDir" ] && \
	MonoServerRootDir="/usr/lib/xsp/test"
	[ -z "$MonoApplications" ] && \
	MonoApplications="/mono:/usr/lib/xsp/test,/:."
	[ -z "$UnixSocketFileName" ] && \
	UnixSocketFileName="/tmp/mod_mono_server"
	[ -z "$MonoServerAddress" ] && \
	MonoServerAddress=127.0.0.1
	[ -z "$MonoServerPort" ] && \
	MonoServerPort=8080
	[ -z "$MonoServerVersion" ] && \
	MonoServerVersion=1

	MONO_SERVER_OPTS="--root ${MonoServerRootDir} \
--applications ${MonoApplications} --nonstop"

	[ -n "$MonoApplicationsConfigDir" ] && \
	MONO_SERVER_OPTS="${MONO_SERVER_OPTS} \
--appconfigdir ${MonoApplicationsConfigDir}"

	case "$MonoServerChannel" in
	"tcp" )
		MONO_SERVER_OPTS="${MONO_SERVER_OPTS} \
--address ${MonoServerAddress} --port ${MonoServerPort}"
		;;
	
	"unix" )
		[ -f "$UnixSocketFileName" ] && rm -f $UnixSocketFileName
		MONO_SERVER_OPTS="${MONO_SERVER_OPTS} \
--filename ${UnixSocketFileName}"
		;;

	* )
		eerror "Please set a valid value for MonoServerChannel"
		return 1
		;;
	esac

	if [ ${MonoServerVersion} -eq 1 ]; then
		modmonoserverpath=1.0/mod-mono-server.exe
	elif [ ${MonoServerVersion} -eq 2 ]; then
		modmonoserverpath=2.0/mod-mono-server2.exe
	elif [ ${MonoServerVersion} -eq 4 ]; then
		modmonoserverpath=4.0/mod-mono-server4.exe
	else
		eerror "MonoServerVersion was not properly set. Check your /etc/conf.d/mod-mono-server"
		return 1
	fi

	export MONO_SHARED_DIR=/tmp

	ebegin "Starting mod-mono-server"

	start-stop-daemon --quiet --start \
		--background \
		--make-pidfile \
		--pidfile /var/run/aspnet/mod-mono-server.pid \
		--user aspnet \
		--exec /usr/bin/mono /usr/lib/mono/${modmonoserverpath} \
		-- $MONO_SERVER_OPTS

	eend $?
}

stop() {
	ebegin "Stopping mod-mono-server"

	start-stop-daemon --quiet --stop \
		--pidfile /var/run/aspnet/mod-mono-server.pid

	eend $?
}
