# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/ekg/ekg-0.4.0.0.ebuild,v 1.1 2014/07/02 07:57:51 gienah Exp $

EAPI=5

# ebuild generated by hackport 0.4.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Remote monitoring of processes"
HOMEPAGE="https://github.com/tibbe/ekg"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="<dev-haskell/aeson-0.8:=[profile?]
	>=dev-haskell/ekg-core-0.1:=[profile?] <dev-haskell/ekg-core-0.2:=[profile?]
	<dev-haskell/network-2.6:=[profile?]
	<dev-haskell/snap-core-0.10:=[profile?]
	<dev-haskell/snap-server-0.10:=[profile?]
	<dev-haskell/text-1.2:=[profile?]
	<dev-haskell/transformers-0.5:=[profile?]
	<dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_prepare() {
	cabal_chdeps \
		'transformers < 0.4' 'transformers < 0.5'
}
