#!/sbin/runscript

depend() {
	need net
	use logger mysql
}

start() {
	ebegin "Starting SSH Proxy daemon"
	start-stop-daemon --start --background \
		--pidfile /var/run/sshproxyd.pid --exec /usr/bin/sshproxyd -- \
		--daemon --user ${SSHPROXYD_USER:-sshproxy} \
		--config-dir ${SSHPROXYD_CONFDIR:-/etc/sshproxy} \
		--pid /var/run/sshproxyd.pid
	eend $?
}

stop() {
	ebegin "Stopping SSH Proxy daemon"
	start-stop-daemon --quiet --stop --pidfile /var/run/sshproxyd.pid
	eend $?
}
