#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

DAEMON=/usr/sbin/x2gocleansessions
PIDFILE=/run/x2goserver.pid

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
		--exec ${DAEMON} -- $DAEMON_OPTS

	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
	eend $?
}
