#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

start() {
	ebegin "Starting rtl_tcp"
	start-stop-daemon --start --quiet --pidfile /run/rtl_tcp.pid \
		--background --make-pidfile --exec /usr/bin/rtl_tcp \
    -1 /var/log/rtl_tcp.log -2 /var/log/rtl_tcp.log \
		-- ${RTL_TCP_OPTIONS}
	eend ${?}
}

stop() {
	ebegin "Stopping rtl_tcp"
	start-stop-daemon --stop --quiet --pidfile /run/rtl_tcp.pid
	eend ${?}
}
