#!/sbin/openrc-run
# Copyright 2019 Sony Interactive Entertainment Inc.
# Distributed under the terms of the GNU General Public License v2

description="netbox daemon"
command=/usr/bin/gunicorn
command_args="-c /etc/netbox/gunicorn_config.py netbox.wsgi"
command_user=netbox:netbox
directory=/opt/netbox/netbox
error_log=/var/log/netbox/"${RC_SVCNAME}".log
output_log=/var/log/netbox/"${RC_SVCNAME}".log
supervisor=supervise-daemon
