#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start() {
	ebegin "Starting oops"
	/usr/sbin/oopsctl start &> /dev/null
	eend $?
}

status() {
	if service_started "${myservice}"; then
		/usr/sbin/oopsctl stat
	fi
	return 0
}

stop() {
	ebegin "Stopping oops"
	/usr/sbin/oopsctl stop &> /dev/null
	eend $?
}
