#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/mail-mta/opensmtpd/files/smtpd.initd,v 1.3 2013/11/20 05:16:56 zx2c4 Exp $

command="smtpd"
start_stop_daemon_args="--pidfile=/var/run/smtpd.pid"
description="SMTP daemon from OpenBSD"

depend() {
	need net
}
stop() {
	ebegin "Stopping smtpd"
	smtpctl stop
	eend $?
}
