# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Bindings to the ICU library"
HOMEPAGE="https://github.com/haskell/text-icu"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
RESTRICT=test # QuickCheck occasionally finds counterexamples
# and fails to build: Duplicate instance declarations: instance NFData Ordering

RDEPEND=">=dev-lang/ghc-9.0.2:=
	dev-libs/icu
	dev-haskell/text:=[profile?]
	|| ( ( >=dev-haskell/text-0.9.1.0 <dev-haskell/text-1.3 )
		( >=dev-haskell/text-2.0 <dev-haskell/text-2.2 ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	virtual/pkgconfig
	test? ( >=dev-haskell/hunit-1.2
		>=dev-haskell/quickcheck-2.4
		dev-haskell/random
		>=dev-haskell/test-framework-0.4
		>=dev-haskell/test-framework-hunit-0.2
		>=dev-haskell/test-framework-quickcheck2-0.2
		dev-haskell/text )
"
