#!/sbin/openrc-run
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	use net
	before inetd xinetd
	provide portmap
}

start() {
	ebegin "Starting rpcbind"
	start-stop-daemon --start --quiet --exec /sbin/rpcbind -- ${RPCBIND_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping rpcbind"
	start-stop-daemon --stop --quiet --exec /sbin/rpcbind
	eend $?
}
