#!/sbin/openrc-run
# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

depend() {
	use dns bareos-fd bareos-sd
}

start_pre() {
	checkpath --directory --owner root:bareos --mode 01775 /run/bareos
}

start_post() {
	ewaitfile 10 /run/bareos/bareos-dir.9101.pid
	checkpath --file --owner root:bareos /run/bareos/bareos-dir.9101.pid
}

command="/usr/sbin/bareos-dir"
command_args="${DIR_OPTIONS}"
pidfile="/run/bareos/bareos-dir.9101.pid"
