#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	use dns
}

start() {
	ebegin "Starting bareos file daemon"
	checkpath -d -m 0750 /run/bareos
	start-stop-daemon --start --quiet --exec /usr/sbin/bareos-fd \
		-- ${FD_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping bareos file daemon"
	start-stop-daemon --stop --quiet --pidfile /run/bareos/bareos-fd.*.pid
	eend $?
}
