#!/sbin/openrc-run
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

depend() {
	need localmount
	use net
}

description="Starts endlessh tarpit"

command="/usr/bin/endlessh"
command_args="${ENDLESSH_ARGS}"
command_background="true"
extra_started_commands="reload"
pidfile="/run/${RC_SVCNAME}.pid"

reload() {
	ebegin "Reloading ${RC_SVCNAME} configuration"
	start-stop-daemon --exec $command --signal HUP
	eend $?
}
