#!/sbin/openrc-run
# Copyright 2015-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Real-time monitor and web admin for Celery distributed task queue"
pidfile=${pidfile:-"/run/${RC_SVCNAME}.pid"}
command="/usr/libexec/${RC_SVCNAME}/${RC_SVCNAME}"
command_user="${RC_SVCNAME}"
command_background="true"
start_stop_daemon_args="--stdout /var/log/${RC_SVCNAME}/${RC_SVCNAME}.log
	--stderr /var/log/${RC_SVCNAME}/${RC_SVCNAME}.log"

depend() {
	need net
}
