# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Dockerfile Linter JavaScript API"
HOMEPAGE="https://github.com/hadolint/hadolint"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
	>=dev-haskell/gitrev-1.3.1:=[profile?]
	>=dev-haskell/language-docker-6.0.4:=[profile?] <dev-haskell/language-docker-7:=[profile?]
	>=dev-haskell/megaparsec-6.4:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/optparse-applicative-0.14.0:=[profile?]
	>=dev-haskell/split-0.2:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/void:=[profile?]
	dev-haskell/yaml:=[profile?]
	>=dev-lang/ghc-8.0.2:=
	>=dev-util/shellcheck-0.5.0:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.2.0
	test? ( dev-haskell/hspec
		>=dev-haskell/hunit-1.2 )
"

src_prepare() {
	default
	sed -i -e "s/-static//" ${PN}.cabal || die
}
