(add-to-list 'load-path "@SITELISP@")
(autoload 'password-store-edit "password-store" nil t)
(autoload 'password-store-copy "password-store" nil t)
(autoload 'password-store-init "password-store" nil t)
(autoload 'password-store-insert "password-store" nil t)
(autoload 'password-store-generate "password-store" nil t)
(autoload 'password-store-remove "password-store" nil t)
(autoload 'password-store-rename "password-store" nil t)
(autoload 'password-store-version "password-store" nil t)
