#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start() {
	ebegin "Starting ARP sponge"
	start-stop-daemon --start --quiet --exec /usr/sbin/arpsponge \
		-- --daemon ${ARPSPONGE_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ARP sponge"
	start-stop-daemon --stop --quiet -n arpsponge
	eend $?
}
