#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

description="umurmurd - A minimalistic mumble server"
pidfile="/run/umurmurd/umurmurd.pid"
command="/usr/bin/umurmurd"
command_args="-c /etc/umurmur/umurmur.conf -p ${pidfile} ${UMURMURD_OPTS}"
start_stop_daemon_args="-p ${pidfile} -w 100"

depend() {
	need net
	use logger
}

start_pre() {
	checkpath -d -o murmur ${pidfile%/*}
}
