--- src/Makefile	2005-05-18 13:26:10.000000000 +0200
+++ src/Makefile.new	2005-05-18 13:26:27.000000000 +0200
@@ -57,12 +57,12 @@
 # Change JAVAC variable to your java compiler.
 # Change JAVAFLAGS variable to any java flags you want to compile with.
 
-JAVAC = jikes
-JAVAFLAGS = -O
-
-#JAVAC = javac
+#JAVAC = jikes
 #JAVAFLAGS = -O
 
+JAVAC = javac
+JAVAFLAGS = -O
+
 JAVACOMPILE = $(JAVAC) -d "$(LIBPATH)" $(JAVAFLAGSCLASSPATH) $(JAVAFLAGS)
 
 # This is the directory the gnu.regexp JAR file will be installed in when
