# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/tagsoup/tagsoup-0.13.3-r1.ebuild,v 1.1 2015/05/01 19:43:24 slyfox Exp $

EAPI=5

# ebuild generated by hackport 0.4.4.9999

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Parsing and extracting information from (possibly malformed) HTML/XML documents"
HOMEPAGE="http://community.haskell.org/~ndm/tagsoup/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="download testprog"

RDEPEND="dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	download? ( dev-haskell/network:=[profile?] )
	testprog? ( >=dev-haskell/quickcheck-2.4:2=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_prepare() {
	cabal_chdeps \
		'executable tagsoup' 'executable haskell-tagsoup'
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag download download) \
		$(cabal_flag testprog testprog)
}
