#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="liquid feedback daemon"
description="Liquid Feedback Frontend"
command=/usr/bin/moonbridge
command_args="-l /var/log/liquid_feedback/lqfb.log /usr/lib/webmcp/bin/mcp.lua /usr/lib/webmcp /var/lib/liquid_feedback_frontend main myconfig-3"
pidfile=/run/lqfb.pid
command_user="apache:apache"
command_background=true

depend() {
  need net
  need postgresql
}
