# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1
# Modified to use a crate tarball instead of listing all crates.

EAPI=8

CRATES="
"

inherit cargo

DESCRIPTION="A very opinionated TUI Matrix client"
HOMEPAGE="https://github.com/PKULAK/matui"
SRC_URI="
https://codeload.github.com/pkulak/matui/tar.gz/refs/tags/v${PV} -> ${P}.tar.gz
https://raw.githubusercontent.com/CharlieKulak/matui/main/${P}-crates.tar.xz
"

LICENSE="GPL-2"
# Dependent crate licenses
LICENSE+="
Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD Boost-1.0
CC0-1.0 CDLA-Permissive-2.0 ISC MIT MPL-2.0 MPL-2.0 UoI-NCSA
Unicode-3.0 Unicode-DFS-2016 WTFPL-2 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"
