#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start() {
	ebegin "Starting MySQL Proxy"
	start-stop-daemon --start --quiet \
		--exec /usr/bin/mysql-proxy \
		-- --daemon --pid-file="${PIDFILE}" ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping MySQL Proxy"
	start-stop-daemon --stop --quiet \
		--pidfile "${PIDFILE}"
	eend $?
}
