#!/sbin/openrc-run
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
           
depend() {
	need clamd
}

start() {
	ebegin "Starting ClamSMTPd"
	start-stop-daemon --start --quiet \
		--exec /usr/sbin/clamsmtpd -- -p /var/run/clamav/clamsmtpd.pid -f /etc/clamsmtpd.conf
	eend $?
}

stop() {
	ebegin "Stopping ClamSMTPd"
	start-stop-daemon --stop --quiet --pidfile /var/run/clamav/clamsmtpd.pid
	eend $?
}
