#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-misc/lcdproc/files/0.5.1-lcdproc.initd,v 1.2 2007/10/04 10:39:36 swegener Exp $

depend(){
	use LCDd
}

start() {
	ebegin "Starting lcdproc"
	start-stop-daemon --start --background \
		--exec /usr/bin/lcdproc
	eend $?
}

stop() {
	ebegin "Stopping lcdproc"
	start-stop-daemon --stop --exec /usr/bin/lcdproc
	eend $?
}
