#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-i18n/skkserv/files/skkserv.initd,v 1.2 2004/07/14 21:28:07 agriffis Exp $

start() {
	ebegin "Starting skkserv"
	start-stop-daemon --start --quiet --exec /usr/sbin/skkserv
	eend $?
}

stop() {
	ebegin "Stopping skkserv"
	start-stop-daemon --stop --quiet --exec /usr/sbin/skkserv
	eend $?
}
