#!/sbin/openrc-run

depend() {
	need net
	use jabber-server
}

start() {
	ebegin "Starting MUC Jabber Transport"
	start-stop-daemon \
		--background \
		--start  \
		--user jabber:jabber \
		--exec /usr/bin/mu-conference \
		-- -c /etc/jabber/mu-conference.xml
	eend $?
}

stop() {
	ebegin "Stoping MUC Jabber Transport"
	start-stop-daemon \
		--stop \
		--pidfile /var/run/jabber/mu-conference.pid
	eend $?
}
