#!/sbin/openrc-run
# Copyright 2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Drone CI Agent"
pidfile=${pidfile:-"/run/drone/${SVCNAME}.pid"}
user=${user:-drone}
group=${group:-drone}

command="/usr/bin/drone-agent"
command_background="true"
start_stop_daemon_args="--user ${user} --group ${group} \
	--stdout /var/log/drone/${SVCNAME}.log \
	--stderr /var/log/drone/${SVCNAME}.log"
