#!/sbin/openrc-run
# Copyright 2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Clair Vulnerability Static Analysis for Containers"
pidfile=${pidfile:-"/run/${RC_SVCNAME}.pid"}
user=${user:-${RC_SVCNAME}}
group=${group:-${RC_SVCNAME}}

command="/usr/bin/clair"
command_args="${command_args:--config=/etc/clair/config.yaml}"
command_background="true"
start_stop_daemon_args="--user ${user} --group ${group} \
	--stdout /var/log/${RC_SVCNAME}/${RC_SVCNAME}.log \
	--stderr /var/log/${RC_SVCNAME}/${RC_SVCNAME}.log"

depend() {
	after net
}
