#!/sbin/openrc-run
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

start() {
	ebegin "Starting DNSSEC control daemon"
	"${ROLLERD_CMD}" --rrfile "${ROLLERD_RRFILE}" \
		-directory "${ROLLERD_KRFDIR}" ${ROLLERD_OPTS}
	eend $? "failed to start rollerd"
}

stop() {
	ebegin "stoping rollerd"
	/usr/bin/rollctl -halt
	eend $? "failed to stop rollerd"
}
