diff -urN wmdl-1.4.1/Makefile wmdl-1.4.1-modified/Makefile
--- Makefile	2009-04-28 16:34:24.000000000 +0200
+++ Makefile.new	2009-04-28 16:33:55.000000000 +0200
@@ -1,23 +1,14 @@
 
-INCLUDES = -I/usr/include \
-           -I/usr/local/include \
-           -I/usr/openwin/share/include/X11
-
-LIBINC =   -L/usr/lib/X11 \
-           -L/usr/X11/lib \
-           -L/usr/X11R6/lib \
-           -L/usr/local/lib/X11 
+INCLUDES =
+
+LIBINC = -L/usr/X11R6/lib
  
 PIXMAPINC = -I./images
 
 LIBS = -lm -lX11 -lXpm -lXext 
 
 
-CC=gcc
-#CC=cc
-
-#CFLAGS= -g --verbose
-CFLAGS= -g
+FLAGS=${CFLAGS}
 
 TARGET=wmdl
 SOURCE=wmdl.c
@@ -25,10 +16,10 @@
 all: ${TARGET}
 
 ${TARGET}: ${SOURCE}
-	$(CC) $(CFLAGS) -o ${TARGET} ${SOURCE} ${INCLUDES} ${LIBINC} ${PIXMAPINC} ${LIBS}
+	$(CC) $(FLAGS) -o ${TARGET} ${SOURCE} ${INCLUDES} ${LIBINC} ${PIXMAPINC} ${LIBS}
 
 clean:
 	if [ -e wmdl ] ; then rm wmdl; fi
 
 install:
-	if [ -e /usr/local/bin ] ; then cp wmdl /usr/local/bin ; fi
+	if [ -e /usr/bin ] ; then cp wmdl /usr/bin ; fi
