#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
	use dns
}

start() {
	ebegin "Starting bacula file daemon"
	start-stop-daemon --start --quiet --exec /usr/sbin/bacula-fd \
		-- ${FD_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping bacula file daemon"
	start-stop-daemon --stop --quiet --pidfile /var/run/bacula-fd.*.pid
	eend $?
}
