#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Purpose License v2
# $Id$

depend() {
   need dbus
}

start() {
   ebegin "Starting oFono"
   start-stop-daemon --start --quiet --exec /usr/sbin/ofonod
   eend $?
}

stop() {
   ebegin "Stopping oFono"
   start-stop-daemon --stop --quiet --exec /usr/sbin/ofonod
   eend $?
}

# vim: set ft=gentoo-init-d ts=3 sw=3 et:
