#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Released under the 2-clause BSD license.

description="Set up tmpfiles.d entries for /dev"

depend()
{
	provide stmpfiles-dev stmpfiles.dev tmpfiles-dev tmpfiles.dev
	use dev-mount
	before dev
	keyword -prefix -vserver
}

start()
{
	ebegin "Setting up tmpfiles.d entries for /dev"
	/bin/systemd-tmpfiles --prefix=/dev --create --boot ${stmpfiles_opts}
	eend $?
}
