#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

PID_FILE="/run/unifi-video.pid"

start() {
	ebegin "Starting unifi-video"
	start-stop-daemon --start --quiet -b \
	--pidfile "${PID_FILE}" -m \
	--exec /usr/sbin/unifi-video start
	eend $?
	#--user nobody --group nobody \
}

stop() {
	ebegin "Stopping unifi-video"
	start-stop-daemon --quiet --stop -R 20 --pidfile "${PID_FILE}"
	eend $?
}
