# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A class of monads which can log messages"
HOMEPAGE="https://github.com/kazu-yamamoto/logger"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/conduit-1.0*:=[profile?]
		>=dev-haskell/fast-logger-0.2:=[profile?]
		<dev-haskell/fast-logger-0.4:=[profile?]
		dev-haskell/monad-control:=[profile?]
		dev-haskell/mtl:=[profile?]
		=dev-haskell/resourcet-0.4*:=[profile?]
		dev-haskell/text:=[profile?]
		dev-haskell/transformers:=[profile?]
		dev-haskell/transformers-base:=[profile?]
		>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
