#!/sbin/runscript
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net
}

start() {
	ebegin "Starting arpon"
	start-stop-daemon --start --background --make-pidfile --pidfile "/var/run/arpon.pid" \
		--exec /usr/sbin/arpon -- ${ARPON_OPTS} >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Stopping arpon"
	start-stop-daemon --stop --pidfile "/var/run/arpon.pid"
	eend $?
}
