#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
        need net
}

start() {
        ebegin "Starting tlswrap"
	start-stop-daemon --start --exec /usr/bin/tlswrap >/dev/null
        eend $?
}

stop() {
        ebegin "Stopping tlswrap"
	start-stop-daemon --stop --exec /usr/sbin/tlswrap
        eend $?
}
