(add-to-list 'load-path "@SITELISP@")
(autoload 'fff-find-file-in-envvar-path			"fff" nil t)
(autoload 'fff-insert-file-in-envvar-path		"fff" nil t)
(autoload 'fff-find-file-in-exec-path			"fff" nil t)
(autoload 'fff-insert-file-in-exec-path			"fff" nil t)
(autoload 'fff-find-file-in-path			"fff" nil t)
(autoload 'fff-insert-file-in-path			"fff" nil t)
(autoload 'fff-find-file-in-locate-db			"fff" nil t)
(autoload 'fff-insert-file-in-locate-db			"fff" nil t)
(autoload 'fff-install-map				"fff" nil t)
(autoload 'fff-find-emacs-lisp-library			"fff-elisp" nil t)
(autoload 'fff-insert-emacs-lisp-library		"fff-elisp" nil t)
(autoload 'fff-locate-emacs-lisp-library		"fff-elisp" nil t)
(autoload 'fff-find-loaded-elisp-function-or-variable	"fff-elisp" nil t)
(autoload 'fff-elisp-install-map			"fff-elisp" nil t)
(autoload 'fff-find-rfc					"fff-rfc" nil t)
(autoload 'fff-rfc-install-map				"fff-rfc" nil t)
