#!/sbin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

MCOLLECTIVE_PID_DIR="${MCOLLECTIVE_PID_DIR:-/var/run/puppetlabs}"

command="/usr/sbin/mcollectived"
pidfile="${MCOLLECTIVE_PID_DIR}/mcollectived.pid"

command_args="--pidfile ${pidfile} --config=/etc/puppetlabs/mcollective/server.cfg --daemonize"

depend() {
    need net
}

start_pre() {
    checkpath --directory "${MCOLLECTIVE_PID_DIR}"
}
