#!/sbin/openrc-run
# Copyright 2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="remotely control an OpenVAS Scanner"
command=/usr/bin/ospd-openvas
pidfile="/run/${RC_SVCNAME}.pid"
command_args="${OSPD_OPENVAS_OPTIONS} \
	${OSPD_OPENVAS_UNIX_SOCKET} \
	${OSPD_OPENVAS_SOCKET_MODE} \
	--pid-file ${pidfile} \
	--config /etc/openvas/ospd.conf"

depend() {
	after bootmisc
	need localmount redis
}

start_pre() {
        checkpath -d /var/run/ospd
}
