# Copyright 2024-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
"

RUST_MIN_VER="1.88.0"
inherit cargo

DESCRIPTION="Stalwart Mail Server command line utility"
HOMEPAGE="https://stalw.art"
SRC_URI="https://github.com/stalwartlabs/cli/archive/refs/tags/v${PV}.tar.gz -> stalwart-cli-${PV}.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://dev.gentoo.org/~lordvan/${P}-crates.tar.xz
	"
fi

S="${WORKDIR}/cli-${PV}"

LICENSE="|| ( AGPL-3 )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 Unicode-3.0
"

# 0.16.x has breaking changes so avoid installing new cli with old server
DEPEND+="
	!!<net-mail/stalwart-mail-0.16.0
"

SLOT="0"
KEYWORDS="~amd64"

src_compile() {
	cargo_src_compile --bin stalwart-cli
}

pkg_postinst() {
	ewarn "If you are upgrading from v0.15.5 and below, this version includes"
	ewarn "breaking changes to the internal directory, calendar and contacts."
	ewarn "Please read the upgrading documentation for more information on "
	ewarn "how to upgrade from previous versions."
	ewarn "It can be found here: https://stalw.art/docs/install/upgrade/"
	ewarn "0.16 upgrade instructions are here:"
	ewarn "https://github.com/stalwartlabs/stalwart/blob/main/UPGRADING/v0_16.md"
}
