#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start() {
	ebegin "Starting distributed.net personal proxy"
	start-stop-daemon --start --quiet --pidfile /opt/proxyper/rc5desproxy.pid --exec /opt/proxyper/proxyper -- -detach
	eend $?
}

stop() {
	ebegin "Stopping distributed.net personal proxy"
	start-stop-daemon --stop --quiet --pidfile /opt/proxyper/rc5desproxy.pid
	eend $?
}
