<?php
/* Autoloader for dev-php/phpunit-6.5.5 and its dependencies */

$include_dir = '/usr/share/php';

if (!class_exists('Fedora\\Autoloader\\Autoload', false)) {
    require_once "${include_dir}/Fedora/Autoloader/autoload.php";
}

\Fedora\Autoloader\Autoload::addClassMap(
    array(
   'phpunit\\builder\\identity' => '/Builder/Identity.php',
   'phpunit\\builder\\invocationmocker' => '/Builder/InvocationMocker.php',
   'phpunit\\builder\\match' => '/Builder/Match.php',
   'phpunit\\builder\\methodnamematch' => '/Builder/MethodNameMatch.php',
   'phpunit\\builder\\namespacematch' => '/Builder/NamespaceMatch.php',
   'phpunit\\builder\\parametersmatch' => '/Builder/ParametersMatch.php',
   'phpunit\\builder\\stub' => '/Builder/Stub.php',
   'phpunit\\exception\\badmethodcallexception' => '/Exception/BadMethodCallException.php',
   'phpunit\\exception\\exception' => '/Exception/Exception.php',
   'phpunit\\exception' => '/Exception.php',
   'phpunit\\exception' => '/Exception.php',
   'phpunit\\exception\\runtimeexception' => '/Exception/RuntimeException.php',
   'phpunit\\forwardcompatibility\\mockobject' => '/ForwardCompatibility/MockObject.php',
   'phpunit\\framework\\assert' => '/Framework/Assert.php',
   'phpunit\\framework\\assert' => '/Framework/Assert.php',
   'phpunit\\framework\\assert\\functions' => '/Framework/Assert/Functions.php',
   'phpunit\\framework\\assertionfailederror' => '/Framework/AssertionFailedError.php',
   'phpunit\\framework\\assertionfailederror' => '/Framework/AssertionFailedError.php',
   'phpunit\\framework\\basetestlistener' => '/Framework/BaseTestListener.php',
   'phpunit\\framework\\basetestlistener' => '/Framework/BaseTestListener.php',
   'phpunit\\framework\\codecoverageexception' => '/Framework/CodeCoverageException.php',
   'phpunit\\framework\\codecoverageexception' => '/Framework/CodeCoverageException.php',
   'phpunit\\framework\\constraint\\arrayhaskey' => '/Framework/Constraint/ArrayHasKey.php',
   'phpunit\\framework\\constraint\\arrayhaskey' => '/Framework/Constraint/ArrayHasKey.php',
   'phpunit\\framework\\constraint\\arraysubset' => '/Framework/Constraint/ArraySubset.php',
   'phpunit\\framework\\constraint\\arraysubset' => '/Framework/Constraint/ArraySubset.php',
   'phpunit\\framework\\constraint\\attribute' => '/Framework/Constraint/Attribute.php',
   'phpunit\\framework\\constraint\\attribute' => '/Framework/Constraint/Attribute.php',
   'phpunit\\framework\\constraint\\callback' => '/Framework/Constraint/Callback.php',
   'phpunit\\framework\\constraint\\callback' => '/Framework/Constraint/Callback.php',
   'phpunit\\framework\\constraint\\classhasattribute' => '/Framework/Constraint/ClassHasAttribute.php',
   'phpunit\\framework\\constraint\\classhasattribute' => '/Framework/Constraint/ClassHasAttribute.php',
   'phpunit\\framework\\constraint\\classhasstaticattribute' => '/Framework/Constraint/ClassHasStaticAttribute.php',
   'phpunit\\framework\\constraint\\classhasstaticattribute' => '/Framework/Constraint/ClassHasStaticAttribute.php',
   'phpunit\\framework\\constraint\\composite' => '/Framework/Constraint/Composite.php',
   'phpunit\\framework\\constraint\\composite' => '/Framework/Constraint/Composite.php',
   'phpunit\\framework\\constraint\\constraint' => '/Framework/Constraint/Constraint.php',
   'phpunit\\framework\\constraint\\count' => '/Framework/Constraint/Count.php',
   'phpunit\\framework\\constraint\\count' => '/Framework/Constraint/Count.php',
   'phpunit\\framework\\constraint\\directoryexists' => '/Framework/Constraint/DirectoryExists.php',
   'phpunit\\framework\\constraint\\directoryexists' => '/Framework/Constraint/DirectoryExists.php',
   'phpunit\\framework\\constraint\\exceptioncode' => '/Framework/Constraint/ExceptionCode.php',
   'phpunit\\framework\\constraint\\exceptioncode' => '/Framework/Constraint/ExceptionCode.php',
   'phpunit\\framework\\constraint\\exception' => '/Framework/Constraint/Exception.php',
   'phpunit\\framework\\constraint\\exception' => '/Framework/Constraint/Exception.php',
   'phpunit\\framework\\constraint\\exceptionmessage' => '/Framework/Constraint/ExceptionMessage.php',
   'phpunit\\framework\\constraint\\exceptionmessage' => '/Framework/Constraint/ExceptionMessage.php',
   'phpunit\\framework\\constraint\\exceptionmessageregularexpression' => '/Framework/Constraint/ExceptionMessageRegularExpression.php',
   'phpunit\\framework\\constraint\\fileexists' => '/Framework/Constraint/FileExists.php',
   'phpunit\\framework\\constraint\\fileexists' => '/Framework/Constraint/FileExists.php',
   'phpunit\\framework\\constraint\\greaterthan' => '/Framework/Constraint/GreaterThan.php',
   'phpunit\\framework\\constraint\\greaterthan' => '/Framework/Constraint/GreaterThan.php',
   'phpunit\\framework\\constraint\\isanything' => '/Framework/Constraint/IsAnything.php',
   'phpunit\\framework\\constraint\\isanything' => '/Framework/Constraint/IsAnything.php',
   'phpunit\\framework\\constraint\\isempty' => '/Framework/Constraint/IsEmpty.php',
   'phpunit\\framework\\constraint\\isempty' => '/Framework/Constraint/IsEmpty.php',
   'phpunit\\framework\\constraint\\isequal' => '/Framework/Constraint/IsEqual.php',
   'phpunit\\framework\\constraint\\isequal' => '/Framework/Constraint/IsEqual.php',
   'phpunit\\framework\\constraint\\isfalse' => '/Framework/Constraint/IsFalse.php',
   'phpunit\\framework\\constraint\\isfalse' => '/Framework/Constraint/IsFalse.php',
   'phpunit\\framework\\constraint\\isfinite' => '/Framework/Constraint/IsFinite.php',
   'phpunit\\framework\\constraint\\isfinite' => '/Framework/Constraint/IsFinite.php',
   'phpunit\\framework\\constraint\\isidentical' => '/Framework/Constraint/IsIdentical.php',
   'phpunit\\framework\\constraint\\isidentical' => '/Framework/Constraint/IsIdentical.php',
   'phpunit\\framework\\constraint\\isinfinite' => '/Framework/Constraint/IsInfinite.php',
   'phpunit\\framework\\constraint\\isinfinite' => '/Framework/Constraint/IsInfinite.php',
   'phpunit\\framework\\constraint\\isinstanceof' => '/Framework/Constraint/IsInstanceOf.php',
   'phpunit\\framework\\constraint\\isinstanceof' => '/Framework/Constraint/IsInstanceOf.php',
   'phpunit\\framework\\constraint\\isjson' => '/Framework/Constraint/IsJson.php',
   'phpunit\\framework\\constraint\\isjson' => '/Framework/Constraint/IsJson.php',
   'phpunit\\framework\\constraint\\isnan' => '/Framework/Constraint/IsNan.php',
   'phpunit\\framework\\constraint\\isnan' => '/Framework/Constraint/IsNan.php',
   'phpunit\\framework\\constraint\\isnull' => '/Framework/Constraint/IsNull.php',
   'phpunit\\framework\\constraint\\isnull' => '/Framework/Constraint/IsNull.php',
   'phpunit\\framework\\constraint\\isreadable' => '/Framework/Constraint/IsReadable.php',
   'phpunit\\framework\\constraint\\isreadable' => '/Framework/Constraint/IsReadable.php',
   'phpunit\\framework\\constraint\\istrue' => '/Framework/Constraint/IsTrue.php',
   'phpunit\\framework\\constraint\\istrue' => '/Framework/Constraint/IsTrue.php',
   'phpunit\\framework\\constraint\\istype' => '/Framework/Constraint/IsType.php',
   'phpunit\\framework\\constraint\\istype' => '/Framework/Constraint/IsType.php',
   'phpunit\\framework\\constraint\\iswritable' => '/Framework/Constraint/IsWritable.php',
   'phpunit\\framework\\constraint\\iswritable' => '/Framework/Constraint/IsWritable.php',
   'phpunit\\framework\\constraint\\jsonmatcheserrormessageprovider' => '/Framework/Constraint/JsonMatchesErrorMessageProvider.php',
   'phpunit\\framework\\constraint\\jsonmatches' => '/Framework/Constraint/JsonMatches.php',
   'phpunit\\framework\\constraint\\jsonmatches' => '/Framework/Constraint/JsonMatches.php',
   'phpunit\\framework\\constraint\\lessthan' => '/Framework/Constraint/LessThan.php',
   'phpunit\\framework\\constraint\\lessthan' => '/Framework/Constraint/LessThan.php',
   'phpunit\\framework\\constraint\\logicaland' => '/Framework/Constraint/LogicalAnd.php',
   'phpunit\\framework\\constraint\\logicalnot' => '/Framework/Constraint/LogicalNot.php',
   'phpunit\\framework\\constraint\\logicalor' => '/Framework/Constraint/LogicalOr.php',
   'phpunit\\framework\\constraint\\logicalxor' => '/Framework/Constraint/LogicalXor.php',
   'phpunit\\framework\\constraint\\objecthasattribute' => '/Framework/Constraint/ObjectHasAttribute.php',
   'phpunit\\framework\\constraint\\objecthasattribute' => '/Framework/Constraint/ObjectHasAttribute.php',
   'phpunit\\framework\\constraint\\regularexpression' => '/Framework/Constraint/RegularExpression.php',
   'phpunit\\framework\\constraint\\samesize' => '/Framework/Constraint/SameSize.php',
   'phpunit\\framework\\constraint\\samesize' => '/Framework/Constraint/SameSize.php',
   'phpunit\\framework\\constraint\\stringcontains' => '/Framework/Constraint/StringContains.php',
   'phpunit\\framework\\constraint\\stringcontains' => '/Framework/Constraint/StringContains.php',
   'phpunit\\framework\\constraint\\stringendswith' => '/Framework/Constraint/StringEndsWith.php',
   'phpunit\\framework\\constraint\\stringendswith' => '/Framework/Constraint/StringEndsWith.php',
   'phpunit\\framework\\constraint\\stringmatchesformatdescription' => '/Framework/Constraint/StringMatchesFormatDescription.php',
   'phpunit\\framework\\constraint\\stringstartswith' => '/Framework/Constraint/StringStartsWith.php',
   'phpunit\\framework\\constraint\\stringstartswith' => '/Framework/Constraint/StringStartsWith.php',
   'phpunit\\framework\\constraint\\traversablecontains' => '/Framework/Constraint/TraversableContains.php',
   'phpunit\\framework\\constraint\\traversablecontains' => '/Framework/Constraint/TraversableContains.php',
   'phpunit\\framework\\constraint\\traversablecontainsonly' => '/Framework/Constraint/TraversableContainsOnly.php',
   'phpunit\\framework\\constraint\\traversablecontainsonly' => '/Framework/Constraint/TraversableContainsOnly.php',
   'phpunit\\framework\\coveredcodenotexecutedexception' => '/Framework/CoveredCodeNotExecutedException.php',
   'phpunit\\framework\\coveredcodenotexecutedexception' => '/Framework/CoveredCodeNotExecutedException.php',
   'phpunit\\framework\\dataprovidertestsuite' => '/Framework/DataProviderTestSuite.php',
   'phpunit\\framework\\error\\deprecated' => '/Framework/Error/Deprecated.php',
   'phpunit\\framework\\error\\deprecated' => '/Framework/Error/Deprecated.php',
   'phpunit\\framework\\error\\error' => '/Framework/Error/Error.php',
   'phpunit\\framework\\error\\notice' => '/Framework/Error/Notice.php',
   'phpunit\\framework\\error\\notice' => '/Framework/Error/Notice.php',
   'phpunit\\framework\\error\\warning' => '/Framework/Error/Warning.php',
   'phpunit\\framework\\error\\warning' => '/Framework/Error/Warning.php',
   'phpunit\\framework\\exception' => '/Framework/Exception.php',
   'phpunit\\framework\\exception' => '/Framework/Exception.php',
   'phpunit\\framework\\exceptionwrapper' => '/Framework/ExceptionWrapper.php',
   'phpunit\\framework\\exceptionwrapper' => '/Framework/ExceptionWrapper.php',
   'phpunit\\framework\\expectationfailedexception' => '/Framework/ExpectationFailedException.php',
   'phpunit\\framework\\expectationfailedexception' => '/Framework/ExpectationFailedException.php',
   'phpunit\\framework\\incompletetestcase' => '/Framework/IncompleteTestCase.php',
   'phpunit\\framework\\incompletetestcase' => '/Framework/IncompleteTestCase.php',
   'phpunit\\framework\\incompletetesterror' => '/Framework/IncompleteTestError.php',
   'phpunit\\framework\\incompletetesterror' => '/Framework/IncompleteTestError.php',
   'phpunit\\framework\\incompletetest' => '/Framework/IncompleteTest.php',
   'phpunit\\framework\\incompletetest' => '/Framework/IncompleteTest.php',
   'phpunit\\framework\\invalidcoverstargetexception' => '/Framework/InvalidCoversTargetException.php',
   'phpunit\\framework\\invalidcoverstargetexception' => '/Framework/InvalidCoversTargetException.php',
   'phpunit\\framework\\missingcoversannotationexception' => '/Framework/MissingCoversAnnotationException.php',
   'phpunit\\framework\\missingcoversannotationexception' => '/Framework/MissingCoversAnnotationException.php',
   'phpunit\\framework\\outputerror' => '/Framework/OutputError.php',
   'phpunit\\framework\\outputerror' => '/Framework/OutputError.php',
   'phpunit\\framework\\riskytesterror' => '/Framework/RiskyTestError.php',
   'phpunit\\framework\\riskytesterror' => '/Framework/RiskyTestError.php',
   'phpunit\\framework\\riskytest' => '/Framework/RiskyTest.php',
   'phpunit\\framework\\riskytest' => '/Framework/RiskyTest.php',
   'phpunit\\framework\\selfdescribing' => '/Framework/SelfDescribing.php',
   'phpunit\\framework\\selfdescribing' => '/Framework/SelfDescribing.php',
   'phpunit\\framework\\skippedtestcase' => '/Framework/SkippedTestCase.php',
   'phpunit\\framework\\skippedtestcase' => '/Framework/SkippedTestCase.php',
   'phpunit\\framework\\skippedtesterror' => '/Framework/SkippedTestError.php',
   'phpunit\\framework\\skippedtesterror' => '/Framework/SkippedTestError.php',
   'phpunit\\framework\\skippedtest' => '/Framework/SkippedTest.php',
   'phpunit\\framework\\skippedtest' => '/Framework/SkippedTest.php',
   'phpunit\\framework\\skippedtestsuiteerror' => '/Framework/SkippedTestSuiteError.php',
   'phpunit\\framework\\skippedtestsuiteerror' => '/Framework/SkippedTestSuiteError.php',
   'phpunit\\framework\\syntheticerror' => '/Framework/SyntheticError.php',
   'phpunit\\framework\\syntheticerror' => '/Framework/SyntheticError.php',
   'phpunit\\framework\\testcase' => '/Framework/TestCase.php',
   'phpunit\\framework\\testcase' => '/Framework/TestCase.php',
   'phpunit\\framework\\testfailure' => '/Framework/TestFailure.php',
   'phpunit\\framework\\testfailure' => '/Framework/TestFailure.php',
   'phpunit\\framework\\test' => '/Framework/Test.php',
   'phpunit\\framework\\test' => '/Framework/Test.php',
   'phpunit\\framework\\testlistenerdefaultimplementation' => '/Framework/TestListenerDefaultImplementation.php',
   'phpunit\\framework\\testlistener' => '/Framework/TestListener.php',
   'phpunit\\framework\\testlistener' => '/Framework/TestListener.php',
   'phpunit\\framework\\testresult' => '/Framework/TestResult.php',
   'phpunit\\framework\\testresult' => '/Framework/TestResult.php',
   'phpunit\\framework\\testsuite' => '/Framework/TestSuite.php',
   'phpunit\\framework\\testsuite' => '/Framework/TestSuite.php',
   'phpunit\\framework\\testsuiteiterator' => '/Framework/TestSuiteIterator.php',
   'phpunit\\framework\\unintentionallycoveredcodeerror' => '/Framework/UnintentionallyCoveredCodeError.php',
   'phpunit\\framework\\unintentionallycoveredcodeerror' => '/Framework/UnintentionallyCoveredCodeError.php',
   'phpunit\\framework\\warning' => '/Framework/Warning.php',
   'phpunit\\framework\\warning' => '/Framework/Warning.php',
   'phpunit\\framework\\warningtestcase' => '/Framework/WarningTestCase.php',
   'phpunit\\framework\\warningtestcase' => '/Framework/WarningTestCase.php',
   'phpunit\\generator' => '/Generator.php',
   'phpunit\\invocation\\invocation' => '/Invocation/Invocation.php',
   'phpunit\\invocationmocker' => '/InvocationMocker.php',
   'phpunit\\invocation\\objectinvocation' => '/Invocation/ObjectInvocation.php',
   'phpunit\\invocation\\staticinvocation' => '/Invocation/StaticInvocation.php',
   'phpunit\\invokable' => '/Invokable.php',
   'phpunit\\matcher\\anyinvokedcount' => '/Matcher/AnyInvokedCount.php',
   'phpunit\\matcher\\anyparameters' => '/Matcher/AnyParameters.php',
   'phpunit\\matcher\\consecutiveparameters' => '/Matcher/ConsecutiveParameters.php',
   'phpunit\\matcher\\invocation' => '/Matcher/Invocation.php',
   'phpunit\\matcher\\invokedatindex' => '/Matcher/InvokedAtIndex.php',
   'phpunit\\matcher\\invokedatleastcount' => '/Matcher/InvokedAtLeastCount.php',
   'phpunit\\matcher\\invokedatleastonce' => '/Matcher/InvokedAtLeastOnce.php',
   'phpunit\\matcher\\invokedatmostcount' => '/Matcher/InvokedAtMostCount.php',
   'phpunit\\matcher\\invokedcount' => '/Matcher/InvokedCount.php',
   'phpunit\\matcher\\invokedrecorder' => '/Matcher/InvokedRecorder.php',
   'phpunit\\matcher' => '/Matcher.php',
   'phpunit\\matcher\\methodname' => '/Matcher/MethodName.php',
   'phpunit\\matcher\\parameters' => '/Matcher/Parameters.php',
   'phpunit\\matcher\\statelessinvocation' => '/Matcher/StatelessInvocation.php',
   'phpunit\\mockbuilder' => '/MockBuilder.php',
   'phpunit\\mockobject' => '/MockObject.php',
   'phpunit\\runner\\basetestrunner' => '/Runner/BaseTestRunner.php',
   'phpunit\\runner\\basetestrunner' => '/Runner/BaseTestRunner.php',
   'phpunit\\runner\\exception' => '/Runner/Exception.php',
   'phpunit\\runner\\exception' => '/Runner/Exception.php',
   'phpunit\\runner\\filter\\excludegroupfilteriterator' => '/Runner/Filter/ExcludeGroupFilterIterator.php',
   'phpunit\\runner\\filter\\factory' => '/Runner/Filter/Factory.php',
   'phpunit\\runner\\filter\\factory' => '/Runner/Filter/Factory.php',
   'phpunit\\runner\\filter\\groupfilteriterator' => '/Runner/Filter/GroupFilterIterator.php',
   'phpunit\\runner\\filter\\includegroupfilteriterator' => '/Runner/Filter/IncludeGroupFilterIterator.php',
   'phpunit\\runner\\filter\\namefilteriterator' => '/Runner/Filter/NameFilterIterator.php',
   'phpunit\\runner\\phpttestcase' => '/Runner/PhptTestCase.php',
   'phpunit\\runner\\standardtestsuiteloader' => '/Runner/StandardTestSuiteLoader.php',
   'phpunit\\runner\\standardtestsuiteloader' => '/Runner/StandardTestSuiteLoader.php',
   'phpunit\\runner\\testsuiteloader' => '/Runner/TestSuiteLoader.php',
   'phpunit\\runner\\testsuiteloader' => '/Runner/TestSuiteLoader.php',
   'phpunit\\runner\\version' => '/Runner/Version.php',
   'phpunit\\runner\\version' => '/Runner/Version.php',
   'phpunit\\stub\\consecutivecalls' => '/Stub/ConsecutiveCalls.php',
   'phpunit\\stub\\exception' => '/Stub/Exception.php',
   'phpunit\\stub\\matchercollection' => '/Stub/MatcherCollection.php',
   'phpunit\\stub\\returnargument' => '/Stub/ReturnArgument.php',
   'phpunit\\stub\\returncallback' => '/Stub/ReturnCallback.php',
   'phpunit\\stub\\returnreference' => '/Stub/ReturnReference.php',
   'phpunit\\stub\\returnself' => '/Stub/ReturnSelf.php',
   'phpunit\\stub\\returnstub' => '/Stub/ReturnStub.php',
   'phpunit\\stub\\returnvaluemap' => '/Stub/ReturnValueMap.php',
   'phpunit\\stub' => '/Stub.php',
   'phpunit\\textui\\command' => '/TextUI/Command.php',
   'phpunit\\textui\\command' => '/TextUI/Command.php',
   'phpunit\\textui\\resultprinter' => '/TextUI/ResultPrinter.php',
   'phpunit\\textui\\resultprinter' => '/TextUI/ResultPrinter.php',
   'phpunit\\textui\\testrunner' => '/TextUI/TestRunner.php',
   'phpunit\\textui\\testrunner' => '/TextUI/TestRunner.php',
   'phpunit\\util\\blacklist' => '/Util/Blacklist.php',
   'phpunit\\util\\blacklist' => '/Util/Blacklist.php',
   'phpunit\\util\\configurationgenerator' => '/Util/ConfigurationGenerator.php',
   'phpunit\\util\\configurationgenerator' => '/Util/ConfigurationGenerator.php',
   'phpunit\\util\\configuration' => '/Util/Configuration.php',
   'phpunit\\util\\configuration' => '/Util/Configuration.php',
   'phpunit\\util\\errorhandler' => '/Util/ErrorHandler.php',
   'phpunit\\util\\errorhandler' => '/Util/ErrorHandler.php',
   'phpunit\\util\\fileloader' => '/Util/Fileloader.php',
   'phpunit\\util\\fileloader' => '/Util/Fileloader.php',
   'phpunit\\util\\filesystem' => '/Util/Filesystem.php',
   'phpunit\\util\\filesystem' => '/Util/Filesystem.php',
   'phpunit\\util\\filter' => '/Util/Filter.php',
   'phpunit\\util\\filter' => '/Util/Filter.php',
   'phpunit\\util\\getopt' => '/Util/Getopt.php',
   'phpunit\\util\\getopt' => '/Util/Getopt.php',
   'phpunit\\util\\globalstate' => '/Util/GlobalState.php',
   'phpunit\\util\\globalstate' => '/Util/GlobalState.php',
   'phpunit\\util\\invalidargumenthelper' => '/Util/InvalidArgumentHelper.php',
   'phpunit\\util\\invalidargumenthelper' => '/Util/InvalidArgumentHelper.php',
   'phpunit\\util\\json' => '/Util/Json.php',
   'phpunit\\util\\log\\junit' => '/Util/Log/JUnit.php',
   'phpunit\\util\\log\\junit' => '/Util/Log/JUnit.php',
   'phpunit\\util\\log\\teamcity' => '/Util/Log/TeamCity.php',
   'phpunit\\util\\log\\teamcity' => '/Util/Log/TeamCity.php',
   'phpunit\\util\\php\\abstractphpprocess' => '/Util/PHP/AbstractPhpProcess.php',
   'phpunit\\util\\php\\defaultphpprocess' => '/Util/PHP/DefaultPhpProcess.php',
   'phpunit\\util\\php\\eval-stdin' => '/Util/PHP\\eval-stdin.php',
   'phpunit\\util\\php\\windowsphpprocess' => '/Util/PHP/WindowsPhpProcess.php',
   'phpunit\\util\\printer' => '/Util/Printer.php',
   'phpunit\\util\\printer' => '/Util/Printer.php',
   'phpunit\\util\\regularexpression' => '/Util/RegularExpression.php',
   'phpunit\\util\\testdox\\htmlresultprinter' => '/Util/TestDox/HtmlResultPrinter.php',
   'phpunit\\util\\testdox\\nameprettifier' => '/Util/TestDox/NamePrettifier.php',
   'phpunit\\util\\testdox\\nameprettifier' => '/Util/TestDox/NamePrettifier.php',
   'phpunit\\util\\testdox\\resultprinter' => '/Util/TestDox/ResultPrinter.php',
   'phpunit\\util\\testdox\\resultprinter' => '/Util/TestDox/ResultPrinter.php',
   'phpunit\\util\\testdox\\textresultprinter' => '/Util/TestDox/TextResultPrinter.php',
   'phpunit\\util\\testdox\\xmlresultprinter' => '/Util/TestDox/XmlResultPrinter.php',
   'phpunit\\util\\test' => '/Util/Test.php',
   'phpunit\\util\\test' => '/Util/Test.php',
   'phpunit\\util\\texttestlistrenderer' => '/Util/TextTestListRenderer.php',
   'phpunit\\util\\type' => '/Util/Type.php',
   'phpunit\\util\\type' => '/Util/Type.php',
   'phpunit\\util\\xmltestlistrenderer' => '/Util/XmlTestListRenderer.php',
   'phpunit\\util\\xml' => '/Util/Xml.php',
   'phpunit\\util\\xml' => '/Util/Xml.php',
   'phpunit\\verifiable' => '/Verifiable.php',
),
  "${include_dir}/PHPUnit"
);

// Dependencies
\Fedora\Autoloader\Dependencies::required(array(
  "${include_dir}/File/Iterator/autoload.php",
  "${include_dir}/PHP/CodeCoverage/autoload.php",
  "${include_dir}/PHP/Timer/autoload.php",
  "${include_dir}/SebastianBergmann/Version/autoload.php",
  "${include_dir}/SebastianBergmann/Diff/autoload.php",
  "${include_dir}/SebastianBergmann/Environment/autoload.php",
  "${include_dir}/SebastianBergmann/Exporter/autoload.php",
  "${include_dir}/SebastianBergmann/GlobalState/autoload.php",
  "${include_dir}/SebastianBergmann/Comparator/autoload.php",
  "${include_dir}/SebastianBergmann/ObjectEnumerator/autoload.php",
  "${include_dir}/SebastianBergmann/ResourceOperations/autoload.php",
  "${include_dir}/Symfony/Component/Yaml/autoload.php",
  "${include_dir}/Text/Template/autoload.php",
  "${include_dir}/myclabs/DeepCopy/autoload.php",
  "${include_dir}/PHPUnit/Framework/MockObject/autoload.php",
  "${include_dir}/phpspec/Prophecy/autoload.php",
));
