# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7
DESCRIPTION="A collection of modules for the SWORD project"
HOMEPAGE="https://www.crosswire.org/sword/"

LICENSE="metapackage"
SLOT="0"
KEYWORDS="~amd64 ~ppc ~x86"
IUSE=""

DEPEND=""
RDEPEND="app-dicts/sword-Abbott
	app-dicts/sword-ACV
	app-dicts/sword-Afr1953
	app-dicts/sword-AKJV
	app-dicts/sword-Alb
	app-dicts/sword-Aleppo
	app-dicts/sword-AmTract
	app-dicts/sword-AraSVD
	app-dicts/sword-ArmEastern
	app-dicts/sword-ArmWestern
	app-dicts/sword-ASV
	app-dicts/sword-Barnes
	app-dicts/sword-BasHautin
	app-dicts/sword-BBE
	app-dicts/sword-BulVeren
	app-dicts/sword-BurJudson
	app-dicts/sword-Byz
	app-dicts/sword-CBC
	app-dicts/sword-Chamorro
	app-dicts/sword-Clarke
	app-dicts/sword-Common
	app-dicts/sword-Cro
	app-dicts/sword-CzeBKR
	app-dicts/sword-Daily
	app-dicts/sword-Dan
	app-dicts/sword-Darby
	app-dicts/sword-Diaglott
	app-dicts/sword-DRC
	app-dicts/sword-DTN
	app-dicts/sword-DutKant
	app-dicts/sword-DutSVV
	app-dicts/sword-Easton
	app-dicts/sword-Esperanto
	app-dicts/sword-FarsiOPV
	app-dicts/sword-FinBiblia
	app-dicts/sword-Finney
	app-dicts/sword-FinPR
	app-dicts/sword-FreBBB
	app-dicts/sword-FreCrampon
	app-dicts/sword-FreLSG
	app-dicts/sword-FreMartin
	app-dicts/sword-FreSegond
	app-dicts/sword-Geneva
	app-dicts/sword-Geneva1599
	app-dicts/sword-GerElb1871
	app-dicts/sword-GerElb1905
	app-dicts/sword-GerLut1545
	app-dicts/sword-GerSch
	app-dicts/sword-GreekHebrew
	app-dicts/sword-HebrewGreek
	app-dicts/sword-Heretics
	app-dicts/sword-Hitchcock
	app-dicts/sword-HNV
	app-dicts/sword-HunKar
	app-dicts/sword-Institutes
	app-dicts/sword-ISBE
	app-dicts/sword-ISV
	app-dicts/sword-ItaDio
	app-dicts/sword-ItaRive
	app-dicts/sword-JFB
	app-dicts/sword-Josephus
	app-dicts/sword-JPS
	app-dicts/sword-JST
	app-dicts/sword-Jubilee2000
	app-dicts/sword-KJV
	app-dicts/sword-KJVD
	app-dicts/sword-KLV
	app-dicts/sword-KLVen_iklingon
	app-dicts/sword-KLViklingon_en
	app-dicts/sword-Lightfoot
	app-dicts/sword-LITV
	app-dicts/sword-Luther
	app-dicts/sword-MAK
	app-dicts/sword-ManxGaelic
	app-dicts/sword-MHC
	app-dicts/sword-MHCC
	app-dicts/sword-MKJV
	app-dicts/sword-Montgomery
	app-dicts/sword-Murdock
	app-dicts/sword-Nave
	app-dicts/sword-Norsk
	app-dicts/sword-Orthodoxy
	app-dicts/sword-Packard
	app-dicts/sword-Personal
	app-dicts/sword-Peshitta
	app-dicts/sword-Pilgrim
	app-dicts/sword-PNT
	app-dicts/sword-Practice
	app-dicts/sword-RKJNT
	app-dicts/sword-RNKJV
	app-dicts/sword-Robinson
	app-dicts/sword-Rotherham
	app-dicts/sword-RST
	app-dicts/sword-RusMakarij
	app-dicts/sword-RWebster
	app-dicts/sword-RWP
	app-dicts/sword-SAOA
	app-dicts/sword-Scofield
	app-dicts/sword-ScotsGaelic
	app-dicts/sword-SME
	app-dicts/sword-Smith
	app-dicts/sword-SpaRV
	app-dicts/sword-SpaRVG2004
	app-dicts/sword-SpaSEV
	app-dicts/sword-SpaVNT
	app-dicts/sword-Spurious
	app-dicts/sword-StrongsGreek
	app-dicts/sword-StrongsHebrew
	app-dicts/sword-Swahili
	app-dicts/sword-Tagalog
	app-dicts/sword-TCR
	app-dicts/sword-TDavid
	app-dicts/sword-TFG
	app-dicts/sword-Tisch
	app-dicts/sword-Torrey
	app-dicts/sword-TR
	app-dicts/sword-TSK
	app-dicts/sword-Twenty
	app-dicts/sword-Tyndale
	app-dicts/sword-UKJV
	app-dicts/sword-Ukrainian
	app-dicts/sword-Uma
	app-dicts/sword-Vulgate
	app-dicts/sword-Vulgate_HebPs
	app-dicts/sword-WEB
	app-dicts/sword-Webster
	app-dicts/sword-WebstersDict
	app-dicts/sword-Wesley
	app-dicts/sword-Weymouth
	app-dicts/sword-WHNU
	app-dicts/sword-WLC
	app-dicts/sword-Wulfila
	app-dicts/sword-Wycliffe
	app-dicts/sword-YLT"
