#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

start() {
	ebegin "Starting msfweb"
	start-stop-daemon --start --quiet --background --exec /usr/bin/msfweb \
		--pidfile ${PIDFILE} --make-pidfile -- ${MSF_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping msfweb"
	start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
	rm -f ${PIDFILE}
	eend $?
}
