# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999
#hackport: flags: +systemlib,-use-stat3,-use-stat4,-uri-filenames,-full-text-search,-have-usleep,-json1,-use-pkgconfig

CABAL_FEATURES="lib profile haddock hoogle hscolour" # test-suite
inherit haskell-cabal

DESCRIPTION="Backend for the persistent library using sqlite3"
HOMEPAGE="https://www.yesodweb.com/book/persistent"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
IUSE="build-sanity-exe"

RESTRICT="test" # Test-suite depends on deprecated system-fileio and system-filepath

RDEPEND=">=dev-db/sqlite-3.0
	>=dev-haskell/aeson-1.0:=[profile?]
	>=dev-haskell/conduit-1.2.12:=[profile?]
	>=dev-haskell/microlens-th-0.4.1.1:=[profile?]
	>=dev-haskell/monad-logger-0.3.25:=[profile?]
	>=dev-haskell/persistent-2.15.2.0:=[profile?] <dev-haskell/persistent-3:=[profile?]
	dev-haskell/resource-pool:=[profile?]
	>=dev-haskell/resourcet-1.1.9:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	dev-haskell/unliftio-core:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	virtual/libc
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
#	test? ( dev-haskell/fast-logger
#		>=dev-haskell/hspec-2.4
#		dev-haskell/hunit
#		dev-haskell/microlens
#		dev-haskell/persistent-test
#		dev-haskell/quickcheck
#		dev-haskell/system-fileio
#		dev-haskell/system-filepath
#		dev-haskell/temporary )

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag build-sanity-exe build-sanity-exe) \
		--flag=-full-text-search \
		--flag=-have-usleep \
		--flag=-json1 \
		--flag=systemlib \
		--flag=-uri-filenames \
		--flag=-use-pkgconfig \
		--flag=-use-stat3 \
		--flag=-use-stat4
}
