#!/sbin/openrc-run
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Id$

depend() {
	use net
	need cman
}

start() {
	ebegin "Starting the Quorum Disk Daemon"
	start-stop-daemon --start --quiet --exec /usr/sbin/qdiskd -- -Q
	eend $? "Failed to start qdiskd"
}

stop() {
	ebegin "Stopping the Quorum Disk Daemon"
	start-stop-daemon --stop --pidfile /var/run/qdiskd.pid
	eend $? "Failed to stop qdiskd"
}
