#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Starts ${SVCNAME} service for OpenStack"

command=/usr/bin/${SVCNAME}
command_user="${HEAT_USER:-heat}"
command_background=yes
command_args="--config-file /etc/heat/heat.conf --log-file ${HEAT_LOGDIR:-/var/log/heat}/${SVCNAME}.log"
pidfile=/run/${SVCNAME}.pid
required_files=/etc/heat/heat.conf

depend() {
    need net 
}
