#!/sbin/openrc-run
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	use logger
	need net
}

start() {
	ebegin "Starting up-imapproxy"
	start-stop-daemon --start --quiet --exec /usr/sbin/imapproxyd
	eend $?
}

stop() {
	ebegin "Stopping up-imapproxy"
	start-stop-daemon --stop --quiet --exec /usr/sbin/imapproxyd
	eend $?
}
