#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start()	{
	ebegin "Starting Nylon"
	start-stop-daemon --start --quiet --pidfile /var/run/nylon.pid \
		--startas /usr/bin/nylon 
	eend $?
}

stop()	{
	ebegin "Stopping Nylon"
	start-stop-daemon --stop --quiet --pidfile /var/run/nylon.pid
	eend $?
}


