#!/sbin/openrc-run
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

pidfile="/var/run/sagan/sagan.pid"
command="/usr/bin/sagan"
command_args="-D \"${SAGAN_OPTS}\" -u \"${SAGAN_USER}\""

depend() {
      use logger mysql postgresql
      need localmount
}

start_pre() {
    checkpath -d -o sagan /var/run/sagan
    checkpath -p -o sagan -m 0644 /var/run/sagan/sagan.fifo
}
