#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="OpenVAS Manager"
command=/usr/sbin/openvasmd
command_args="${OPENVAS_MANAGER_OPTIONS} ${OPENVAS_MANAGER_PORT} ${OPENVAS_MANAGER_LISTEN_ADDRESS} ${OPENVAS_MANAGER_SCANNER_HOST} ${OPENVAS_MANAGER_GNUTLS_PRIORITIES}"
pidfile="/var/run/openvasmd.pid"

depend() {
	after bootmisc
	need localmount net openvassd
}
