#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

name="OpenVAS Manager"
command=/usr/sbin/openvasmd
command_args="${MANAGER_LISTEN} ${MANAGER_PORT} ${SCANNER_LISTEN} ${SCANNER_PORT} ${MANAGER_EXTRA_ARGS}"
pidfile="/run/openvasmd.pid"

depend() {
	after bootmisc
	need localmount net openvassd
}

start_pre() {
	checkpath --directory --mode 0775 --quiet /var/cache/openvas
}
