#!/sbin/openrc-run
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net snmptrapd
}
				
start() {
	ebegin "Starting snmptt"
	start-stop-daemon --start --pidfile /var/run/snmptt.pid --exec /usr/sbin/snmptt
	eend
}

stop() {
	ebegin "Stopping snmptt"
	start-stop-daemon  --stop --pidfile /var/run/snmptt.pid
	eend
}		
