# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/c2hs/c2hs-0.20.1.ebuild,v 1.1 2014/12/23 04:39:24 gienah Exp $

EAPI=5

# ebuild generated by hackport 0.4.3

CABAL_FEATURES="bin test-suite"
inherit haskell-cabal

DESCRIPTION="C->Haskell FFI tool that gives some cross-language type safety"
HOMEPAGE="https://github.com/haskell/c2hs"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	dev-haskell/dlist
	>=dev-haskell/language-c-0.4.7 <dev-haskell/language-c-0.5
	>=dev-lang/ghc-7.4.1
	test? ( dev-haskell/hunit
		dev-haskell/test-framework
		dev-haskell/test-framework-hunit
		dev-haskell/transformers
		>=dev-haskell/shelly-1.0
		dev-haskell/text
		>=dev-haskell/yaml-0.8 )
"
