#!/sbin/openrc-run
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

opts="start stop restart"

depend() {
	need net
}

start() {
	ebegin "Starting tac_plus"
	start-stop-daemon --start --quiet --exec /usr/bin/tac_plus \
		-- -C /etc/tac_plus/tac_plus.conf ${TAC_PLUS_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping tac_plus"
	start-stop-daemon --stop --quiet --pidfile /var/run/tac_plus.pid
	eend $?
}
