#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need localmount
}

start_pre() {
	if [ ! -e /etc/openct.conf ] ; then
		eerror "You need an /etc/openct.conf file to run OpenCT"
		return 1
	fi
	checkpath -d -m 0750 -o openctd:openct /var/run/openct
}

start() {
	ebegin "Starting OpenCT"
	/usr/sbin/openct-control init
	eend $?
}

stop() {
	ebegin "Stopping OpenCT"
	/usr/sbin/openct-control shutdown
	eend $?
}
