# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Support for serialising Haskell to and from JSON"
HOMEPAGE="http://hackage.haskell.org/package/json"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~ppc64 ~x86 ~amd64-linux"
IUSE="mapdict +parsec +pretty"

RDEPEND="dev-haskell/mtl:=[profile?]
	>=dev-haskell/syb-0.3.3:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	parsec? ( dev-haskell/parsec:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

PATCHES=( "${FILESDIR}"/${PN}-0.9.3-ghc-8.8.patch )

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag mapdict mapdict) \
		$(cabal_flag parsec parsec) \
		$(cabal_flag pretty pretty)
}
