# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="swap and assoc: Symmetric and Semigroupy Bifunctors"
HOMEPAGE="https://hackage.haskell.org/package/assoc"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
IUSE="+tagged"

RDEPEND=">=dev-lang/ghc-9.0.2:=
	tagged? ( >=dev-haskell/tagged-0.8.8:=[profile?] <dev-haskell/tagged-0.9:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

src_prepare() {
	default

	cabal-mksetup
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag tagged tagged)
}
