#!/sbin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net
}

start() {
	ebegin "Starting iscsid"
	start-stop-daemon --start --quiet --exec \
		/usr/sbin/iscsid -- $iscsidopts
	eend $? "Error starting iscsid"
}

stop() {
	ebegin "Stopping iscsid"
	start-stop-daemon --stop --quiet --exec /usr/sbin/iscsid
	eend $? "Error stopping iscsid"
}
