#!/sbin/runscript
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net nfs
}

start() {
	ebegin "Starting nfsuserd"
	start-stop-daemon --start --quiet --exec \
		/usr/sbin/nfsuserd -- $nfsuserdopts
	eend $? "Error starting nfsuserd"
}

stop() {
	ebegin "Stopping nfsuserd"
	start-stop-daemon --stop --quiet --exec /usr/sbin/nfsuserd
	eend $? "Error stopping nfsuserd"
}
