#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

SCCACHE_SCHEDULER_CONF="${SCCACHE_SCHEDULER_CONF:-/etc/sccache/scheduler.conf}"

depend() {
	need localmount
	use net
}

description="Starts sccache build scheduler server"

command="/usr/bin/sccache-dist"
command_args="scheduler ${SCCACHE_SCHEDULER_CONF:+--config ${SCCACHE_SCHEDULER_CONF}}"
command_background="true"
pidfile="/run/${RC_SVCNAME}.pid"
required_files="${SCCACHE_SCHEDULER_CONF}"
start_stop_daemon_args="--env RUST_LOG=${SCCACHE_SCHEDULER_LOGLEVEL:- }"
