#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

SCCACHE_SERVER_CONF="${SCCACHE_SERVER_CONF:-/etc/sccache/server.conf}"

depend() {
	need localmount
	use net
}

description="Starts sccache build server"

command="/usr/bin/sccache-dist"
command_args="server ${SCCACHE_SERVER_CONF:+--config ${SCCACHE_SERVER_CONF}}"
command_background="true"
pidfile="/run/${RC_SVCNAME}.pid"
required_files="${SCCACHE_SERVER_CONF}"
start_stop_daemon_args="--env RUST_LOG=${SCCACHE_SERVER_LOGLEVEL:- }"
