#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

MINBIF_EXEC="/usr/bin/minbif"

depend() {
	need logger net
}

start() {
	ebegin "Starting minbif"
	start-stop-daemon --start --startas ${MINBIF_EXEC} \
		-c minbif:minbif --exec ${MINBIF_EXEC} -- \
		/etc/minbif/minbif.conf
	eend $?
}

stop() {
	ebegin "Stopping minbif"
	start-stop-daemon --stop --exec ${MINBIF_EXEC}
	eend $?
}
