#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/pnp4nagios/files/npcd.initd,v 1.1 2012/07/22 21:45:07 idl0r Exp $

extra_started_commands="reload"

command="/usr/bin/npcd"
command_args="-f /etc/pnp/npcd.cfg -d"

depend() {
	need net
}

reload() {
        ebegin "Reloading npcd"
        kill -HUP `pgrep npcd`
        eend $? "Failed to reload npcd"
}
