# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0
#hackport: flags: -allow-unsafe-gc,-apicheck,-export-dynamic,-lua501,-lua502,-lua_32bits,-system-lua,-pkg-config

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Bindings to Lua, an embeddable scripting language"
HOMEPAGE="https://hslua.org/"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
IUSE="executable"

RDEPEND=">=dev-haskell/hslua-aeson-2.3.1:=[profile?] <dev-haskell/hslua-aeson-2.4:=[profile?]
	>=dev-haskell/hslua-classes-2.2.1:=[profile?] <dev-haskell/hslua-classes-2.4:=[profile?]
	>=dev-haskell/hslua-core-2.3.2:=[profile?] <dev-haskell/hslua-core-2.4:=[profile?]
	>=dev-haskell/hslua-marshalling-2.3.1:=[profile?] <dev-haskell/hslua-marshalling-2.4:=[profile?]
	>=dev-haskell/hslua-objectorientation-2.5:=[profile?] <dev-haskell/hslua-objectorientation-2.6:=[profile?]
	>=dev-haskell/hslua-packaging-2.4:=[profile?] <dev-haskell/hslua-packaging-2.5:=[profile?]
	>=dev-haskell/hslua-typing-0.2:=[profile?] <dev-haskell/hslua-typing-0.3:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	executable? ( dev-haskell/hslua-cli:=[profile?]
			dev-haskell/hslua-module-path:=[profile?]
			dev-haskell/hslua-module-system:=[profile?]
			dev-haskell/hslua-module-text:=[profile?]
			dev-haskell/hslua-module-version:=[profile?]
			dev-haskell/hslua-module-zip:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/tasty-0.11
		dev-haskell/tasty-hslua
		>=dev-haskell/tasty-hunit-0.9
		>=dev-haskell/text-1.2 <dev-haskell/text-2.2 )
"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-allow-unsafe-gc \
		--flag=-apicheck \
		$(cabal_flag executable executable) \
		--flag=-export-dynamic \
		--flag=-lua501 \
		--flag=-lua502 \
		--flag=-lua_32bits \
		--flag=-pkg-config \
		--flag=-system-lua
}
