#!/sbin/openrc-run
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

[ -e /etc/conf.d/nfs ] && . /etc/conf.d/nfs

depend() {
	use ypbind net
	need portmap rpc.pipefs
	after quota
}

start() {
	ebegin "Starting gssd"
	start-stop-daemon --start --exec /usr/sbin/rpc.gssd -- ${OPTS_RPC_GSSD}
	eend $?
}

stop() {
	ebegin "Stopping gssd"
	start-stop-daemon --stop --exec /usr/sbin/rpc.gssd
	eend $?
}
