#!/sbin/openrc-run
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

[ -e /etc/conf.d/nfs ] && . /etc/conf.d/nfs

rpc_bin=/usr/sbin/rpc.idmapd

depend() {
	use ypbind net
	need portmap
	need rpc.pipefs
	after quota
}

start() {
	ebegin "Starting idmapd"
	${rpc_bin} ${OPTS_RPC_IDMAPD}
	eend $? "make sure DNOTIFY support is enabled ..."
}

stop() {
	ebegin "Stopping idmapd"
	start-stop-daemon --stop --exec ${rpc_bin}
	eend $?
}
