# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999
#hackport: flags: -dev,-has-icu,-has-llvm,-bench-show,-use-gauge

CABAL_HACKAGE_REVISION=9

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Unicode normalization"
HOMEPAGE="https://github.com/composewell/unicode-transforms"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"

CABAL_CHDEPS=(
	'bytestring   >= 0.9 && < 0.13' 'bytestring   >= 0.9'
	'text         >=1.1.1 && <=1.2.5.0 || >=2.0 && <2.2' 'text         >=1.1.1'
)

RDEPEND="
	>=dev-haskell/text-1.1.1:=[profile?]
	>=dev-haskell/unicode-data-0.2:=[profile?] <dev-haskell/unicode-data-0.9:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/hspec-2.0 <dev-haskell/hspec-3
		>=dev-haskell/quickcheck-2.1 <dev-haskell/quickcheck-2.18
		>=dev-haskell/split-0.2 <dev-haskell/split-0.3
		dev-haskell/text )
"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-bench-show \
		--flag=-dev \
		--flag=-gauge \
		--flag=-has-icu \
		--flag=-has-llvm
}
