# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.10

EAPI=8

CRATES="
	adler@1.0.2
	ahash@0.7.6
	android_system_properties@0.1.5
	ansi_term@0.12.1
	atty@0.2.14
	autocfg@1.1.0
	base64@0.13.1
	bitflags@1.3.2
	bumpalo@3.12.0
	byteorder@1.4.3
	cc@1.0.78
	cfg-if@1.0.0
	chrono@0.4.23
	clap@2.34.0
	codespan-reporting@0.11.1
	core-foundation-sys@0.8.3
	crc32fast@1.3.2
	crossbeam-utils@0.8.14
	cxx-build@1.0.88
	cxx@1.0.88
	cxxbridge-flags@1.0.88
	cxxbridge-macro@1.0.88
	flate2@1.0.25
	form_urlencoded@1.1.0
	fs2@0.4.3
	fuchsia-cprng@0.1.1
	gcc@0.3.55
	getrandom@0.2.8
	hashbrown@0.12.3
	hermit-abi@0.1.19
	hermit-abi@0.2.6
	hex@0.4.3
	iana-time-zone-haiku@0.1.1
	iana-time-zone@0.1.53
	idna@0.3.0
	jobserver@0.1.25
	js-sys@0.3.60
	lazy_static@1.4.0
	libc@0.2.139
	link-cplusplus@1.0.8
	log@0.4.17
	miniz_oxide@0.6.2
	num-integer@0.1.45
	num-traits@0.2.15
	num_cpus@1.15.0
	once_cell@1.17.0
	paste@1.0.11
	percent-encoding@2.2.0
	ppv-lite86@0.2.17
	proc-macro2@1.0.50
	quote@1.0.23
	rand@0.3.23
	rand@0.4.6
	rand@0.8.5
	rand_chacha@0.3.1
	rand_core@0.3.1
	rand_core@0.4.2
	rand_core@0.6.4
	rdrand@0.4.0
	ring@0.16.20
	rmp-serde@0.15.5
	rmp@0.8.11
	rust-crypto@0.2.36
	rustc-serialize@0.3.24
	rustls@0.20.8
	same-file@1.0.6
	scratch@1.0.3
	sct@0.7.0
	serde@1.0.152
	serde_derive@1.0.152
	spin@0.5.2
	strsim@0.8.0
	syn@1.0.107
	termcolor@1.2.0
	textwrap@0.11.0
	time@0.1.45
	tinyvec@1.6.0
	tinyvec_macros@0.1.0
	unicode-bidi@0.3.10
	unicode-ident@1.0.6
	unicode-normalization@0.1.22
	unicode-width@0.1.10
	untrusted@0.7.1
	ureq@2.6.2
	url@2.3.1
	vec_map@0.8.2
	version_check@0.9.4
	walkdir@2.3.2
	wasi@0.10.0+wasi-snapshot-preview1
	wasi@0.11.0+wasi-snapshot-preview1
	wasm-bindgen-backend@0.2.83
	wasm-bindgen-macro-support@0.2.83
	wasm-bindgen-macro@0.2.83
	wasm-bindgen-shared@0.2.83
	wasm-bindgen@0.2.83
	web-sys@0.3.60
	webpki-roots@0.22.6
	webpki@0.22.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	zstd-safe@4.1.3+zstd.1.5.1
	zstd-sys@1.6.2+zstd.1.5.1
	zstd@0.9.2+zstd.1.5.1
"

inherit cargo

ELFSHAKER_COMMIT="9b65a536ed25d698311b7298332900c54967aa97"
DESCRIPTION="Stores binary objects efficiently"
HOMEPAGE="https://github.com/elfshaker/elfshaker"
SRC_URI="
	https://github.com/elfshaker/elfshaker/archive/${ELFSHAKER_COMMIT}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"
S="${WORKDIR}"/${PN}-${ELFSHAKER_COMMIT}

LICENSE="Apache-2.0"
# Dependent crate licenses
LICENSE+=" Apache-2.0 ISC MIT MPL-2.0 Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"

QA_FLAGS_IGNORED="usr/bin/elfshaker"
