#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Starts ${SVCNAME} service for OpenStack"

command=/usr/bin/${SVCNAME}
command_background=yes
command_args="--config-file /etc/cinder/cinder.conf --log-file ${CINDER_LOGDIR:-/var/log/cinder}/${SVCNAME}.log"
command_user="${CINDER_USER:-cinder}"
pidfile=/run/${SVCNAME}.pid
required_files=/etc/cinder/cinder.conf
retry="SIGTERM/30"

depend() {
	need net
}
