#!/sbin/openrc-run

# Note: the "Foreground" option in clamd.conf must be set to "no"
command="/usr/sbin/clamd"
extra_started_commands="reload"

# For now, must be manually synchronized with the PidFile variable
# in clamd.conf.
#
# https://bugzilla.clamav.net/show_bug.cgi?id=12595
#
pidfile="/run/${RC_SVCNAME}.pid"

start_pre() {
  # This exists to support the (disabled) default LocalSocket setting
  # within clamd.conf. The "clamav" user and group agree with the
  # (disabled) default "User" and "LocalSocketGroup" settings in
  # clamd.conf. And everything here agrees with the
  # clamav-daemon.socket systemd service.
  #
  # Creating this directory is harmless even when a local socket is
  # not used.
  checkpath --directory \
           --mode 0755 \
           --owner clamav:clamav \
           "/run/clamav"
}

reload() {
  ebegin "Reloading ${RC_SVCNAME}"
  "/usr/bin/clamdscan" --reload
  eend $?
}
