.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" This documentation may be distributed under the terms of
.\" the GNU General Public Licence version 2.
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH wmix 1 "Jul 19, 2004" "Michele Noberasco"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wmix \- Dockapp mixer for OSS or ALSA


.SH SYNOPSIS
.B wmix
.RI "{ " options " }"


.SH DESCRIPTION
.B wmix
Dockapp mixer for OSS or ALSA. Allows toggling record source,
muting individual channels, adjusting volume and balance, all in a
compact dockapp size, with TV\-like on\-screen\-display for volume levels.
.LP 
Supports mousewheel to adjust current channelvolume
and can be controlled remotely with SIGUSR1 / SIGUSR2 to adjust the volume.
Keeps a simple configuration file for user\-defined settings.


.SH OPTIONS
.TP 
.BI "\-d " dsp
Connect to remote X display.
.TP 
.BI "\-f " file
Use alternate config file (default is \fI~/.wmixrc\fP)
.TP 
.BI "\-m " dev
Use this mixer device (default  is \fI/dev/mixer\fP)
.TP 
.BI "\-h"
Display list of command line options.
.TP 
.BI "\-v"
Use verbose output messages.
.TP 
.BI "\-e " name
Exclude a channel, can be used many times.


.SH AUTHORS
wmix was written by <timecop@japan.co.jp> and <skunk@mit.edu>
.LP 
This man page was written by Fredrik Steen <stone@debian.org> for the Debian
distribution. Updated and fixed by Michele Noberasco <s4t4n@gentoo.org>
for the Gentoo distribution.
