#!/sbin/openrc-run
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need localmount
}

start() {
	ebegin "Starting smsd"
	start-stop-daemon -b -m -p /var/run/smsd.pid -c smsd:sms --start --exec /usr/bin/smsd -- \
		-c /etc/smsd.conf
	eend ${?}
}

stop() {
	ebegin "Stopping smsd"
	start-stop-daemon --stop -p /var/run/smsd.pid
	eend ${?}
}
