#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-emulation/spice-vdagent/files/spice-vdagent.initd,v 1.3 2011/08/15 00:42:13 jer Exp $

depend() {
    after dbus
}

PIDFILE="/var/run/spice-vdagentd/spice-vdagentd.pid"

start() {
    ebegin "Checking for required modules and devices"

    if [[ ! -d /sys/module/uinput ]] ; then
        eerror "Module 'uinput' not loaded or not enabled in the kernel"
        eend 1
        return 1
    fi

    if [[ ! -c "${PORT}" ]] ; then
        eerror "Required virtio port does not exist. Make sure you"
        eerror "started the virtual machine with appropriate parameters."
        eend 1
        return 1
    fi
    eend 0

    # recreate the directory since /var/run may reside on a ramdisk
    mkdir -p /var/run/spice-vdagentd

    # cleanup stalled socket
    rm -f /var/run/spice-vdagentd/spice-vdagent-sock

    ebegin "Starting spice VD agent daemon"
    start-stop-daemon \
        --start \
        --pidfile "${PIDFILE}" \
        --exec /usr/sbin/spice-vdagentd \
        -- ${SPICE_VDAGENT_ARGS}
    eend $?
}

stop() {
    ebegin "Stopping spice VD agent daemon"
    start-stop-daemon \
        --stop \
        --pidfile "${PIDFILE}"
    eend $?
}
