#!/sbin/openrc-run
# Copyright 2016-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Prometheus apache metrics exporter"
pidfile=${pidfile:-"/run/${RC_SVCNAME}.pid"}
user=${user:-${RC_SVCNAME}}
group=${group:-${RC_SVCNAME}}

command="/usr/bin/apache_exporter"
command_args="${command_args:-}"
command_background="true"
start_stop_daemon_args="--user ${user} --group ${group} \
	--stdout /var/log/apache_exporter/${RC_SVCNAME}.log \
	--stderr /var/log/apache_exporter/${RC_SVCNAME}.log"

depend() {
	after net
}

start_pre() {
	checkpath -q -d -m 0755 -o ${user}:${group} /var/log/apache_exporter
}
