#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later

command="capsh"
command_args="--inh=cap_net_bind_service --user=stubby -- -c '/usr/bin/stubby -g ${STUBBY_OPTS}'"
pidfile="/var/run/stubby/stubby.pid"
name="DNS Privacy Daemon"

depend()
{
	provide dns
	need localmount net
	after bootmisc
	use logger
}

start_pre()
{
	checkpath -d -m 1755 -o stubby:stubby /var/run/stubby
}
