#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	use logger 
	need clamd
}

start() {
	ebegin "Starting clamfs"
	start-stop-daemon --start --quiet \
		--exec /usr/bin/clamfs -- ${CLAMFS_CONFFILE}
	eend $? "Failed to start clamfs"
}

stop() {
	ebegin "Stopping clamfs"
	start-stop-daemon --stop --quiet --name clamfs
	eend $? "Failed to stop clamfs"
}
