# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

TEXLIVE_MODULE_CONTENTS="adigraph aobs-tikz askmaps asyfig asypictureb autoarea bardiag beamerswitch binarytree blochsphere bloques blox bodegraph bondgraph bondgraphs braids bxeepic cachepic callouts celtic chemfig combinedgraphics circuit-macros circuitikz curve curve2e curves dcpic diagmac2 ditaa doc-pictex dottex  dratex drs duotenzor dynkin-diagrams ecgdraw eepic ellipse endofproofwd  epspdfconversion esk euflag fast-diagram fig4latex fitbox flowchart forest genealogytree getmap gincltex gnuplottex gradientframe grafcet graph35 graphicxpsd graphviz gtrlib-largetrees harveyballs here hf-tikz hobby hvfloat istgame kblocks knitting knittingpattern ladder lapdf latex-make lpic lroundrect luamesh luasseq maker makeshape mathspic milsymb miniplot mkpic modiagram neuralnetwork numericplots pb-diagram penrose petri-nets  pgf-blur pgf-cmykshadings pgf-soroban pgf-spectra pgf-umlcd pgf-umlsd pgfgantt pgfkeyx pgfmolbio pgfmorepages pgfopts pgfplots picinpar pict2e pictex pictex2 pinlabel pixelart pmgraph postage prerex productbox ptolemaicastronomy pxpgfmark qcircuit quantikz qrcode randbild randomwalk realhats reotex rviewport sa-tikz schemabloc scsnowman scratch scratch3 setdeck simpleoptics signchart smartdiagram spath3 spectralsequences swimgraf table-fct texdraw ticollege tipfr tikz-3dplot tikz-bayesnet tikz-cd tikz-dependency tikz-dimline tikz-feynhand tikz-feynman tikz-imagelabels tikz-inet tikz-kalender tikz-karnaugh tikz-ladder tikz-layers tikz-nef tikz-network tikz-opm tikz-optics tikz-page tikz-palattice tikz-qtree tikz-relay tikz-sfc tikz-timing tikz-trackschematic tikz-truchet tikzcodeblocks tikzducks tikzinclude tikzlings tikzmark tikzmarmots tikzorbital tikzpagenodes tikzpfeile tikzpeople tikzposter tikzscale tikzsymbols timing-diagrams tqft tkz-base tkz-doc tkz-euclide tkz-orm tsemlines tufte-latex venndiagram visualpstricks xpicture xypic collection-pictures
"
TEXLIVE_MODULE_DOC_CONTENTS="adigraph.doc aobs-tikz.doc askmaps.doc asyfig.doc asypictureb.doc autoarea.doc bardiag.doc beamerswitch.doc binarytree.doc blochsphere.doc bloques.doc blox.doc bodegraph.doc bondgraph.doc bondgraphs.doc braids.doc bxeepic.doc cachepic.doc callouts.doc celtic.doc chemfig.doc combinedgraphics.doc circuit-macros.doc circuitikz.doc curve.doc curve2e.doc curves.doc dcpic.doc diagmac2.doc ditaa.doc doc-pictex.doc dottex.doc dratex.doc drs.doc duotenzor.doc dynkin-diagrams.doc ecgdraw.doc eepic.doc ellipse.doc endofproofwd.doc epspdfconversion.doc esk.doc euflag.doc fast-diagram.doc fig4latex.doc fitbox.doc flowchart.doc forest.doc genealogytree.doc getmap.doc gincltex.doc gnuplottex.doc gradientframe.doc grafcet.doc graph35.doc graphicxpsd.doc graphviz.doc gtrlib-largetrees.doc harveyballs.doc here.doc hf-tikz.doc hobby.doc hvfloat.doc istgame.doc kblocks.doc knitting.doc knittingpattern.doc ladder.doc lapdf.doc latex-make.doc lpic.doc lroundrect.doc luamesh.doc luasseq.doc maker.doc makeshape.doc mathspic.doc milsymb.doc miniplot.doc mkpic.doc modiagram.doc neuralnetwork.doc numericplots.doc pb-diagram.doc penrose.doc petri-nets.doc pgf-blur.doc pgf-cmykshadings.doc pgf-soroban.doc pgf-spectra.doc pgf-umlcd.doc pgf-umlsd.doc pgfgantt.doc pgfkeyx.doc pgfmolbio.doc pgfmorepages.doc pgfopts.doc pgfplots.doc picinpar.doc pict2e.doc pictex.doc pinlabel.doc pixelart.doc pmgraph.doc postage.doc prerex.doc productbox.doc ptolemaicastronomy.doc pxpgfmark.doc qcircuit.doc quantikz.doc qrcode.doc randbild.doc randomwalk.doc realhats.doc reotex.doc rviewport.doc sa-tikz.doc schemabloc.doc scsnowman.doc scratch.doc scratch3.doc setdeck.doc simpleoptics.doc signchart.doc smartdiagram.doc spath3.doc spectralsequences.doc swimgraf.doc table-fct.doc texdraw.doc ticollege.doc tipfr.doc tikz-3dplot.doc tikz-bayesnet.doc tikz-cd.doc tikz-dependency.doc tikz-dimline.doc tikz-feynhand.doc tikz-feynman.doc tikz-imagelabels.doc tikz-inet.doc tikz-kalender.doc tikz-karnaugh.doc tikz-ladder.doc tikz-layers.doc tikz-nef.doc tikz-network.doc tikz-opm.doc tikz-optics.doc tikz-page.doc tikz-palattice.doc tikz-qtree.doc tikz-relay.doc tikz-sfc.doc tikz-timing.doc tikz-trackschematic.doc tikz-truchet.doc tikzcodeblocks.doc tikzducks.doc tikzinclude.doc tikzlings.doc tikzmark.doc tikzmarmots.doc tikzorbital.doc tikzpagenodes.doc tikzpfeile.doc tikzpeople.doc tikzposter.doc tikzscale.doc tikzsymbols.doc timing-diagrams.doc tqft.doc tkz-base.doc tkz-doc.doc tkz-euclide.doc tkz-orm.doc tufte-latex.doc venndiagram.doc visualpstricks.doc xpicture.doc xypic.doc "
TEXLIVE_MODULE_SRC_CONTENTS="aobs-tikz.source asyfig.source asypictureb.source beamerswitch.source binarytree.source blochsphere.source blox.source bondgraphs.source braids.source celtic.source combinedgraphics.source curve.source curve2e.source curves.source dottex.source ecgdraw.source ellipse.source esk.source euflag.source fitbox.source flowchart.source forest.source gincltex.source gnuplottex.source gradientframe.source graph35.source graphviz.source gtrlib-largetrees.source hf-tikz.source hobby.source latex-make.source lroundrect.source luasseq.source makeshape.source penrose.source pgf-blur.source pgf-cmykshadings.source pgfgantt.source pgfmolbio.source pgfopts.source pgfplots.source pict2e.source pixelart.source postage.source productbox.source ptolemaicastronomy.source qrcode.source randbild.source randomwalk.source realhats.source rviewport.source signchart.source smartdiagram.source spath3.source tikz-imagelabels.source tikz-page.source tikz-timing.source tikz-truchet.source tikzinclude.source tikzmark.source tikzpagenodes.source tikzpfeile.source tikzposter.source tikzscale.source tikzsymbols.source tqft.source venndiagram.source xpicture.source "
inherit  texlive-module
DESCRIPTION="TeXLive Graphics, pictures, diagrams"

LICENSE=" Apache-2.0 BSD-2 GPL-2 CC-BY-SA-4.0 "
SLOT="0"
KEYWORDS="~alpha amd64 arm arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~s390 ~sparc x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~x64-solaris ~x86-solaris"
IUSE=""
DEPEND=">=dev-texlive/texlive-basic-2020
>=dev-tex/pgf-3.0.1
"
RDEPEND="${DEPEND} "
TEXLIVE_MODULE_BINSCRIPTS="
	texmf-dist/scripts/cachepic/cachepic.tlu
	texmf-dist/scripts/fig4latex/fig4latex
	texmf-dist/scripts/mathspic/mathspic.pl
	texmf-dist/scripts/mkpic/mkpic
	texmf-dist/scripts/getmap/getmapdl.lua
	texmf-dist/scripts/petri-nets/pn2pdf
"
