#!/sbin/openrc-run

pidfile="/run/${RC_SVCNAME}.pid"
command="/opt/jellyfin/jellyfin"
command_args="--logdir /var/log/jellyfin --cachedir /var/cache/jellyfin --configdir /etc/jellyfin --datadir /var/lib/jellyfin"
command_user="${RC_SVCNAME}:${RC_SVCNAME}"
command_background=true

start_pre() {
	#  (Commands necessary to prepare to start the service)
	# Ensure that our dirs are correct
	checkpath --directory --owner jellyfin:jellyfin --mode 0775 \
		/var/cache/jellyfin
}
