#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-db/pgagent/files/pgagent.initd,v 1.1 2012/04/28 18:34:11 titanofold Exp $

PGAGENTOPT="-t ${PGA_POLL} -r ${PGA_RETRY} -s ${PGA_LOG} -l ${PGA_LEVEL}"

PGOPT="hostaddr=${PG_HOST} dbname=${PG_DBNAME} user=${PG_USER}"

depend() {
    use net
    need postgresql
}

start() {
    ebegin "Starting pgagent"
    start-stop-daemon --start --exec /usr/bin/pgagent -- ${PGAGENTOPT} ${PGOPT}
    eend $?
}

stop() {
    ebegin "Stopping pgagent"
    start-stop-daemon --stop --name pgagent
    eend $?
}
