#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/usr/sbin/sensord"
pidfile="/run/${RC_SVCNAME}.pid"

: ${SENSORD_SSDARGS:=--wait 1000}
: ${SENSORD_TERMTIMEOUT:=TERM/60/KILL/5}
: ${SENSORD_OPTS:=}

command_args="${SENSORD_OPTS} --pid-file ${pidfile}"
start_stop_daemon_args="${SENSORD_SSDARGS}"
retry="${SENSORD_TERMTIMEOUT}"

depend() {
	need localmount
	use logger lm_sensors
}
