#!/sbin/openrc-run
command=/usr/bin/trickster
command_background=yes
command_group=trickster
command_user=trickster
description="Dashboard Accelerator for Prometheus"
error_log=/var/log/${RC_SVCNAME}/${RC_SVCNAME}.log
output_log=/var/log/${RC_SVCNAME}/${RC_SVCNAME}.log
extra_started_commands=reload
pidfile=/var/run/trickster.pid

depend() {
after net
}

reload() {
	ebegin "Reloading ${RC_SVCNAME}"
	start-stop-daemon --signal HUP --pidfile "${PIDFILE}"
	EEND $?
}
