#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-misc/udpxy/files/udpxy.initd,v 1.1 2012/03/22 11:12:43 pva Exp $

depend() {
	need net
}

start() {
	ebegin "Starting udpxy"
	start-stop-daemon --start --exec /usr/bin/udpxy -- ${UDPXYOPTS}
	eend $?
}

stop() {
	ebegin "Stopping udpxy"
	start-stop-daemon --stop --exec /usr/bin/udpxy
	eend $?
}

