# Copyright 2023-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.7

EAPI=8

CRATES="
	aho-corasick@1.0.2
	anes@0.1.6
	anstyle@1.0.10
	autocfg@1.1.0
	bumpalo@3.13.0
	cast@0.3.0
	cc@1.2.1
	cfg-if@1.0.0
	ciborium-io@0.2.2
	ciborium-ll@0.2.2
	ciborium@0.2.2
	clap@4.5.21
	clap_builder@4.5.21
	clap_lex@0.7.3
	codespan-reporting@0.12.0
	criterion-plot@0.5.0
	criterion@0.6.0
	crossbeam-channel@0.5.8
	crossbeam-deque@0.8.3
	crossbeam-epoch@0.9.15
	crossbeam-utils@0.8.16
	crunchy@0.2.2
	cxx-build@1.0.158
	cxx@1.0.158
	cxxbridge-cmd@1.0.158
	cxxbridge-flags@1.0.158
	cxxbridge-macro@1.0.158
	either@1.9.0
	foldhash@0.1.4
	half@2.4.1
	heck@0.5.0
	hermit-abi@0.3.2
	indoc@2.0.5
	itertools@0.10.5
	itertools@0.13.0
	itoa@1.0.9
	js-sys@0.3.64
	libc@0.2.147
	link-cplusplus@1.0.9
	log@0.4.19
	memchr@2.5.0
	memoffset@0.9.0
	num-traits@0.2.16
	num_cpus@1.16.0
	once_cell@1.18.0
	oorandom@11.1.3
	plotters-backend@0.3.5
	plotters-svg@0.3.5
	plotters@0.3.5
	portable-atomic@1.9.0
	proc-macro2@1.0.89
	pyo3-build-config@0.25.1
	pyo3-ffi@0.25.1
	pyo3-macros-backend@0.25.1
	pyo3-macros@0.25.1
	pyo3@0.25.1
	quote@1.0.37
	rayon-core@1.11.0
	rayon@1.7.0
	regex-automata@0.3.3
	regex-syntax@0.7.4
	regex@1.9.1
	rustversion@1.0.18
	ryu@1.0.15
	same-file@1.0.6
	scopeguard@1.2.0
	scratch@1.0.7
	serde@1.0.174
	serde_derive@1.0.174
	serde_json@1.0.103
	shlex@1.3.0
	strsim@0.11.1
	syn@2.0.87
	target-lexicon@0.13.2
	termcolor@1.2.0
	tinytemplate@1.2.1
	unicode-ident@1.0.11
	unicode-width@0.1.10
	unindent@0.2.3
	walkdir@2.3.3
	wasm-bindgen-backend@0.2.87
	wasm-bindgen-macro-support@0.2.87
	wasm-bindgen-macro@0.2.87
	wasm-bindgen-shared@0.2.87
	wasm-bindgen@0.2.87
	web-sys@0.3.64
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
"

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=maturin
RUST_MIN_VER=1.80
PYTHON_COMPAT=( python3_{11..14} )
inherit cargo distutils-r1 pypi

DESCRIPTION="Python bindings for lzokay library"
HOMEPAGE="
	https://github.com/vlaci/lzallright
	https://pypi.org/project/lzallright
"
# sdist doesn't build (so didn't even get to check re tests)
SRC_URI="https://github.com/vlaci/lzallright/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz"
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT Unicode-DFS-2016 ZLIB
"
SLOT="0"
KEYWORDS="~amd64 ~x86"

QA_FLAGS_IGNORED="usr/lib.*/py.*/site-packages/lzallright/_lzallright.*"

# dev-libs/lzokay is bundled, but it has no .pc (https://github.com/AxioDL/lzokay/issues/9)
# and the cxx crate it uses for binding generation needs sources available.

EPYTEST_PLUGINS=()
distutils_enable_tests pytest
