#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/sguil-sensor/files/sensor_agent.initd,v 1.5 2014/07/16 23:56:11 jer Exp $

depend() {
        need net
}

checkconfig() {
        if [ ! -e /etc/sguil/sensor_agent.conf ] ; then
                eerror "You need an /etc/snort/sensor_agent.conf to run the Sensor Agent"
                return 1
        fi
}

start() {
        checkconfig || return 1
        ebegin "Starting Sensor Agent"
        start-stop-daemon --start -c sguil --quiet --exec /usr/bin/sensor_agent.tcl \
		-- -D -c "/etc/sguil/sensor_agent.conf">/dev/null 2>&1
        eend $?
}

stop() {
        ebegin "Stopping Sensor Agent"
        start-stop-daemon --stop --quiet --pidfile /run/sguil-sensor.pid
        eend $?
}

