#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	use net
}

command="/usr/sbin/omnisync"
command_args="-M ${OMNISYNC_MODE} ${OMNISYNC_ARGS}"

start_pre() {
	if [ -z "${OMNISYNC_MODE}" ] ; then
		eerror 'Configuration incomplete! OMNISYNC_MODE not set'
		return 1
	fi
	return 0
}

# vim: filetype=gentoo-init-d sw=2 ts=2 sts=2 noet:
